In [13]:
from google.colab import drive
drive.mount('/content/drive')

# 设置你的数据目录
base_dir = '/content/drive/MyDrive/Colab Notebooks'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
%pip install pandas numpy tensorflow matplotlib scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.3)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.75.1)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.2.5)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.9)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [24]:
import pandas as pd # 导入 pandas 库，用于数据处理和分析
import numpy as np # 导入 numpy 库，用于数值计算
import os # 导入 os 库，用于文件路径操作
from datetime import datetime # 导入 datetime 模块，用于处理日期和时间
from sklearn.preprocessing import MinMaxScaler # 导入 MinMaxScaler，用于数据缩放
from tensorflow.keras.models import Model # 导入 Model，用于构建 Keras 模型
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, Bidirectional, Concatenate # 导入 Keras 层，用于构建模型
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint # 导入回调函数，用于模型训练过程控制
import matplotlib.pyplot as plt # 导入 matplotlib.pyplot，用于绘制图表
import zipfile # 导入 zipfile 库，用于文件打包

# ✅ 参数设置（放在循环外）
stock_codes = ["002475", "601138","301120", "002115", "603725"]  # 需要处理的股票代码列表
start_date = "20210924"  # 回测/训练数据开始日期
end_date =  "20250925"     #datetime.today().strftime("%Y%m%d") # 回测/训练数据结束日期
window_size = 30  # LSTM模型的时间窗口大小，决定了模型考虑多少天的历史数据进行预测
output_size = 1  # 模型输出大小（预测未来1天收盘价）
chart_dir = "./charts"  # 图表保存目录
model_dir = "./models"  # 模型保存目录
# Only use 159943 as the ETF for all stocks in this run
etf_code = "159943" # 使用固定的 ETF 代码 159943，用于与个股进行联合建模和参考

# ✅ 创建目录
os.makedirs(chart_dir, exist_ok=True)  # 创建图表目录，如果已存在则忽略
os.makedirs(model_dir, exist_ok=True)  # 创建模型目录，如果已存在则忽略

# ✅ 通用函数：标准化列名
def standardize_columns(df):
    # 定义列名映射，将中文列名标准化为英文，方便代码处理
    mapping = {
        "日期": "Date", "股票代码": "Code", "开盘": "Open", "收盘": "Close",
        "最高": "High", "最低": "Low", "成交量": "Volume", "成交额": "Amount",
        "振幅": "Amplitude", "涨跌幅": "ChangePct", "涨跌额": "ChangeAmt", "换手率": "Turnover",
        "opendate": "Date", "netamount": "MainNetInflow", "ratioamount": "MainInflowRatio"
    }
    df.rename(columns=mapping, inplace=True)  # 执行列名重命名
    return df # 返回重命名列名后的 DataFrame

# ✅ 通用函数：计算RSI
def compute_rsi(series, window=14):
    # 计算相对强弱指数（RSI）
    delta = series.diff()  # 计算价格变化
    gain = delta.where(delta > 0, 0).rolling(window).mean()  # 计算平均上涨幅度
    loss = -delta.where(delta < 0, 0).rolling(window).mean()  # 计算平均下跌幅度
    # Avoid division by zero
    rs = gain / loss if not loss.isnull().all() and (loss != 0).any() else 0 # 计算相对强度 RS
    return 100 - (100 / (1 + rs))  # 计算RSI值

# ✅ 通用函数：加载并处理数据
def load_and_prepare_data(code, is_etf=False):
    prefix = code[-6:]  # 提取代码的后六位
    market_prefix = "sz" if code.startswith("0") else "sh"  # 判断市场前缀（深圳/上海）
    # 指定日线数据和资金流数据的完整路径
    daily_path = f"/content/drive/MyDrive/Colab Notebooks/kline/{prefix}_daily.csv"
    # Specify the fund flow path based on whether it's an ETF or stock
    # Assuming funds flow data for ETF is in a specific location if it exists
    if is_etf:
        fundflow_path = f"/content/drive/MyDrive/Colab Notebooks/jiqi_do/{market_prefix}{code}.csv"
    else:
        # Assuming stock funds flow data is in a similar structure
        fundflow_path = f"/content/drive/MyDrive/Colab Notebooks/jiqi_do/{market_prefix}{code}.csv"

    # 检查日线数据文件是否存在，不存在则抛出错误
    if not os.path.exists(daily_path):
        raise FileNotFoundError(f"缺失日线数据文件：{daily_path}")

    df = pd.read_csv(daily_path)  # 加载日线数据
    df = standardize_columns(df) # ✅ 在加载后立即标准化列名
    df["Date"] = pd.to_datetime(df["Date"])  # 将日期列转换为 datetime 对象
    df.set_index("Date", inplace=True)  # 将日期列设置为索引
    df.sort_index(inplace=True)  # 按日期排序

    # ✅ 如果资金流数据文件存在，则加载并合并
    # Added is_etf check for clarification, but the logic is the same for now
    if os.path.exists(fundflow_path):
        try:
            df_fund = pd.read_csv(fundflow_path)  # 加载资金流数据
            df_fund = standardize_columns(df_fund)  # 标准化资金流数据的列名
            df_fund["Date"] = pd.to_datetime(df_fund["Date"])  # 将日期列转换为 datetime 对象
            df_fund.set_index("Date", inplace=True)  # 将日期列设置为索引
            # Ensure only relevant columns are merged
            fund_cols_to_merge = ["MainNetInflow", "MainInflowRatio"] # 定义需要合并的资金流列
            # Check if these columns exist in the fund dataframe before merging
            fund_cols_present = [col for col in fund_cols_to_merge if col in df_fund.columns] # 检查资金流文件中实际存在的列
            if fund_cols_present:
                 df = df.merge(df_fund[fund_cols_present], left_index=True, right_index=True, how="left") # 按日期索引合并资金流数据
            else:
                 print(f"⚠️ Funds flow columns {fund_cols_to_merge} not found in {fundflow_path}") # 如果资金流文件存在但所需列缺失，打印警告
        except Exception as e:
            print(f"⚠️ Error loading or merging funds flow data from {fundflow_path}: {e}") # 如果加载或合并资金流数据出错，打印错误信息


    # ✅ 技术指标构造
    df["MA5"] = df["Close"].rolling(5).mean()  # 计算5日移动平均线
    df["MA10"] = df["Close"].rolling(10).mean()  # 计算10日移动平均线
    df["EMA12"] = df["Close"].ewm(span=12).mean()  # 计算12日指数移动平均线
    df["EMA26"] = df["Close"].ewm(span=26).mean()  # 计算26日指数移动平均线
    df["MACD"] = df["EMA12"] - df["EMA26"]  # 计算MACD线
    df["RSI"] = compute_rsi(df["Close"])  # 计算RSI
    df["Return_1d"] = df["Close"].pct_change()  # 计算1日收益率
    df["Volatility_5d"] = df["Close"].rolling(5).std()  # 计算5日波动率
    df["Weekday"] = df.index.weekday  # 提取星期几 (0=Monday, 6=Sunday)
    df["IsMonthEnd"] = df.index.is_month_end.astype(int)  # 判断是否为月末 (1 if True, 0 if False)

    # ✅ 资金流衍生特征 - Check if funds flow columns exist before calculating
    if 'MainNetInflow' in df.columns and 'MainInflowRatio' in df.columns: # 检查资金流主要列是否存在
         df["MainNetInflow_Smooth"] = df["MainNetInflow"].ewm(span=5).mean()  # 计算资金流的指数平滑
         # Avoid division by zero for normalization
         df["MainNetInflow_Normalized"] = (df["MainNetInflow"] - df["MainNetInflow"].mean()) / (df["MainNetInflow"].std() if df["MainNetInflow"].std() != 0 else 1)  # 资金流标准化
         df["MainNetInflow_Ratio_Change"] = df["MainInflowRatio"].pct_change()  # 资金流比例变化率
         df["MainNetInflow_5d_Std"] = df["MainNetInflow"].rolling(5).std()  # 资金流5日标准差
    else:
         print(f"⚠️ Funds flow data not available for {code} or columns missing. Skipping funds flow feature engineering.") # 如果资金流数据不可用或列缺失，跳过资金流特征工程
         # Drop any funds flow columns that might have been partially merged if the file existed but was malformed
         df = df.drop(columns=["MainNetInflow", "MainInflowRatio"], errors='ignore') # 如果资金流列不存在，从 DataFrame 中移除，避免后续错误


    # No dropna here, return the dataframe with potential NaNs
    return df # 返回处理后的 DataFrame，可能包含 NaN 值

# ✅ 通用函数：构建序列
def create_sequences(data_scaled, close_prices, window_size):
    # 根据窗口大小构建用于LSTM训练的序列数据
    X, y = [], [] # 初始化输入序列 X 和输出目标 y 列表
    for i in range(len(data_scaled) - window_size): # 遍历数据，创建长度为 window_size 的序列
        X.append(data_scaled[i:i+window_size])  # 输入序列：当前窗口内的缩放特征数据
        y.append(close_prices[i+window_size])  # 输出目标：窗口结束后的收盘价
    return np.array(X), np.array(y)  # 返回 numpy 数组格式的输入和输出序列

# ✅ 构建联合模型结构
def build_multi_input_lstm(input_shape_stock, input_shape_etf, output_size=1):
    # 构建多输入的LSTM模型，分别处理个股和ETF数据
    input_stock = Input(shape=input_shape_stock, name="stock_input")  # 个股输入层，shape 为 (时间步长, 个股特征数)
    x1 = Bidirectional(LSTM(64, return_sequences=True))(input_stock)  # 个股双向LSTM层，64个单元，返回完整的序列输出
    x1 = Dropout(0.3)(x1)  # Dropout 层，随机丢弃 30% 的神经元连接，防止过拟合
    x1 = Bidirectional(LSTM(32))(x1)  # 个股双向LSTM层，32个单元，返回最后一个时间步的输出
    x1 = Dropout(0.2)(x1)  # Dropout 层

    input_etf = Input(shape=input_shape_etf, name="etf_input")  # ETF输入层，shape 为 (时间步长, ETF 特征数)
    x2 = Bidirectional(LSTM(32))(input_etf)  # ETF双向LSTM层，32个单元
    x2 = Dropout(0.2)(x2)  # Dropout 层

    x = Concatenate()([x1, x2])  # 将个股和ETF的输出在特征维度上拼接起来
    x = Dense(64, activation='relu')(x)  # 全连接层，64个单元，使用 ReLU 激活函数
    x = Dense(32, activation='relu')(x)  # 全连接层，32个单元，使用 ReLU 激活函数
    output = Dense(output_size)(x)  # 输出层，大小由 output_size 决定，通常为 1 (预测收盘价)

    model = Model(inputs=[input_stock, input_etf], outputs=output)  # 构建模型，指定输入层和输出层
    model.compile(optimizer='adam', loss='mse')  # 编译模型，使用 Adam 优化器和均方误差 (MSE) 作为损失函数
    return model # 返回构建好的模型

# ✅ 模型训练函数
def train_multi_input_model(X_stock, X_etf, y, input_shape_stock, input_shape_etf, model_path, chart_dir, code, step=0):
    # 训练联合输入LSTM模型
    model = build_multi_input_lstm(input_shape_stock, input_shape_etf)  # 构建模型实例

    # 设置模型检查点，用于保存训练过程中损失最优的模型
    checkpoint = ModelCheckpoint(
        filepath=model_path, # 模型保存路径
        monitor='loss',  # 监控训练损失
        save_best_only=True,  # 只保存最优模型
        save_weights_only=False,  # 保存整个模型（包括结构和权重）
        verbose=0  # 不显示保存信息
    )

    # 设置早停回调，当训练损失不再显著下降时停止训练，防止过拟合
    early_stop = EarlyStopping(
        monitor='loss',  # 监控训练损失
        patience=15,  # 在损失没有改善的15个epochs后停止
        restore_best_weights=True,  # 恢复到损失最优的那个epoch的模型权重
        verbose=0  # 不显示早停信息
    )

    # 训练模型
    history = model.fit(
        [X_stock, X_etf], y,  # ✅ 将输入数据X_stock和X_etf打包成列表作为模型的输入
        epochs=150,  # 最大训练轮次
        batch_size=32,  # 批处理大小
        callbacks=[checkpoint, early_stop],  # 使用模型检查点和早停回调
        verbose=0  # 不显示训练进度条
    )

    # ✅ 绘制训练损失图
    plt.figure(figsize=(8, 4))  # 创建图表，指定大小
    plt.plot(history.history['loss'], label='训练损失')  # 绘制训练损失曲线
    plt.title(f"{code} - 第{step}步训练损失曲线")  # 设置图表标题，包含股票代码和步骤
    plt.xlabel("Epoch")  # 设置X轴标签
    plt.ylabel("Loss")  # 设置Y轴标签
    plt.grid(True)  # 显示网格
    plt.legend()  # 显示图例
    # 构建图表保存路径，包含股票代码、日期和步骤
    chart_path = os.path.join(chart_dir, f"{code}_{datetime.today().strftime('%Y-%m-%d')}_step{step}_loss.png")
    plt.tight_layout()  # 调整布局，防止标签重叠
    plt.savefig(chart_path)  # 保存图表到指定路径
    plt.close()  # 关闭图表，释放内存
    print(f"📉 训练损失图已保存：{chart_path}") # 打印图表保存路径
    print(f"✅ 模型训练完成，最终MSE: {history.history['loss'][-1]:.4f}")  # 打印最终训练损失
    return model  # 返回训练好的模型

# ✅ Modified predict_future function to use iterative prediction and accept features_common
def predict_future(model, stock_scaled, etf_scaled, df_raw_stock_aligned, scaler_stock, scaler_etf, features_used_in_scaling_stock, features_used_in_scaling_etf, window_size=30, pred_size=10):
    # Predict future stock prices iteratively
    # model: 训练好的 LSTM 模型
    # stock_scaled: 个股历史数据的缩放后 numpy 数组
    # etf_scaled: ETF 历史数据的缩放后 numpy 数组
    # df_raw_stock_aligned: 用于获取最后一个历史日期的个股原始对齐 DataFrame
    # scaler_stock: 个股数据的 MinMaxScaler
    # scaler_etf: ETF 数据的 MinMaxScaler
    # features_used_in_scaling_stock: 个股数据实际用于缩放的特征列名列表
    # features_used_in_scaling_etf: ETF 数据实际用于缩放的特征列名列表
    # window_size: LSTM 模型的时间窗口大小
    # pred_size: 预测未来的天数

    # Check if there is enough historical data to form initial sequences
    if len(stock_scaled) < window_size or len(etf_scaled) < window_size: # 检查历史数据长度是否足够构建初始序列
        print(f"Warning: Not enough historical data ({len(stock_scaled)} for stock, {len(etf_scaled)} for ETF) to form an initial sequence of size {window_size}. Prediction skipped.") # 打印警告信息
        return pd.DataFrame({"Date": [], "Predicted_Stock_Close": [], "Predicted_ETF_Close": []}) # 如果数据不足，返回空的预测 DataFrame # Return both stock and etf predictions

    # Get the last historical sequences for stock and ETF
    last_stock_sequence = np.copy(stock_scaled[-window_size:]) # 获取个股历史数据的最后 window_size 个时间步作为初始预测输入序列的副本
    last_etf_sequence = np.copy(etf_scaled[-window_size:])   # 获取 ETF 历史数据的最后 window_size 个时间步作为初始预测输入序列的副本

    future_stock_preds = []  # 存储未来预测的个股收盘价
    future_etf_preds = [] # 存储未来预测的 ETF 收盘价

    # Find the index of the 'Close' feature in the scaled data based on the features_used_in_scaling lists
    try:
        close_feature_index_stock = features_used_in_scaling_stock.index("Close") # 在实际用于缩放的个股特征列表中找到 'Close' 列的索引
        close_feature_index_etf = features_used_in_scaling_etf.index("Close") # 在实际用于缩放的 ETF 特征列表中找到 'Close' 列的索引
    except ValueError:
        print("Error: 'Close' feature not found in the provided features_used_in_scaling lists.") # 如果 'Close' 列不存在，打印错误信息
        return pd.DataFrame({"Date": [], "Predicted_Stock_Close": [], "Predicted_ETF_Close": []}) # 返回空的预测 DataFrame

    # Find the index of 'Weekday' and 'IsMonthEnd' for generating future features
    try:
        weekday_feature_index_stock = features_used_in_scaling_stock.index("Weekday") # 获取个股特征列表中的 'Weekday' 索引
        ismonthend_feature_index_stock = features_used_in_scaling_stock.index("IsMonthEnd") # 获取个股特征列表中的 'IsMonthEnd' 索引
    except ValueError:
        print("Warning: 'Weekday' or 'IsMonthEnd' feature not found in the stock features list. Cannot generate future date features for stock.") # 如果缺失，打印警告
        weekday_feature_index_stock = None # 设置索引为 None
        ismonthend_feature_index_stock = None # 设置索引为 None

    try:
        weekday_feature_index_etf = features_used_in_scaling_etf.index("Weekday") # 获取 ETF 特征列表中的 'Weekday' 索引
        ismonthend_feature_index_etf = features_used_in_scaling_etf.index("IsMonthEnd") # 获取 ETF 特征列表中的 'IsMonthEnd' 索引
    except ValueError:
        print("Warning: 'Weekday' or 'IsMonthEnd' feature not found in the ETF features list. Cannot generate future date features for ETF.") # 如果缺失，打印警告
        weekday_feature_index_etf = None # 设置索引为 None
        ismonthend_feature_index_etf = None # 设置索引为 None


    # Get the last date from the raw stock data to generate future dates
    last_historical_date = df_raw_stock_aligned.index[-1] # 获取最后一个历史数据的日期

    # --- 迭代预测未来值 ---
    for k in range(pred_size): # 循环预测未来 pred_size 天
        # ✅ Add check for NaNs/Infinities before prediction
        if np.isnan(last_stock_sequence).any() or np.isinf(last_stock_sequence).any(): # 检查个股输入序列是否包含 NaN 或无穷大
            print(f"Warning: NaN or Infinity found in stock sequence before prediction step {k}. Skipping remaining predictions.") # 打印警告
            break # 如果包含，停止预测
        if np.isnan(last_etf_sequence).any() or np.isinf(last_etf_sequence).any(): # 检查 ETF 输入序列是否包含 NaN 或无穷大
            print(f"Warning: NaN or Infinity found in ETF sequence before prediction step {k}. Skipping remaining predictions.") # 打印警告
            break # 如果包含，停止预测

        # Predict the next step using the current sequences
        # Adjust sequence shape for the model: (batch_size, window_size, num_features)
        # model.predict returns a numpy array, take the first sample's first output
        predicted_scaled_stock_value = model.predict([last_stock_sequence[np.newaxis, :, :], last_etf_sequence[np.newaxis, :, :]], verbose=0)[0][0] # 使用模型预测下一个时间步个股的缩放后收盘价

        # Inverse scale the predicted stock value to get the price in original scale
        # Create a dummy array with one row and the number of features used for stock scaling
        dummy_row_stock = np.zeros((1, len(features_used_in_scaling_stock))) # 创建一个用于反向缩放的临时数组，维度与个股缩放特征数一致
        # Put the predicted scaled value at the 'Close' column index
        dummy_row_stock[0, close_feature_index_stock] = predicted_scaled_stock_value # 将预测的缩放值放入临时数组中对应 'Close' 列的位置
        # Inverse transform the dummy row to get the predicted value in original scale
        predicted_original_stock_row = scaler_stock.inverse_transform(dummy_row_stock) # 对临时数组进行反向缩放
        predicted_original_stock_price = predicted_original_stock_row[0, close_feature_index_stock] # 提取反向缩放后的原始个股收盘价


        future_stock_preds.append(predicted_original_stock_price)  # 将预测的个股收盘价添加到结果列表

        # --- Form the input sequence for the next prediction step ---
        # 构建用于下一个时间步预测的输入序列

        # For stock: remove the oldest element and append the scaled predicted stock value
        # Create a new row for the next sequence step
        next_stock_scaled_row = np.copy(last_stock_sequence[-1, :]) # 复制个股当前序列的最后一行特征作为下一个时间步的新行
        next_stock_scaled_row[close_feature_index_stock] = predicted_scaled_stock_value # 将新行的 'Close' 特征更新为预测的缩放后收盘价

        # ✅ Reshape next_stock_scaled_row to (1, num_features) before vstack
        next_stock_scaled_row_reshaped = next_stock_scaled_row.reshape(1, -1) # 将新行 reshape 为 (1, num_features)

        next_stock_sequence = np.vstack([last_stock_sequence[1:], next_stock_scaled_row_reshaped]) # 将当前序列去掉最旧的一行，并垂直堆叠上新行，形成下一个时间步的个股输入序列


        # For ETF: remove the oldest element and append the next scaled value.
        # For a simple trend reference, let's repeat the last scaled ETF close value.
        # A more advanced approach would involve predicting ETF or using external ETF data.
        last_etf_scaled_close = last_etf_sequence[-1, close_feature_index_etf] # 获取 ETF 当前序列的最后一个缩放后收盘价
        next_etf_scaled_row = np.copy(last_etf_sequence[-1, :]) # 复制 ETF 当前序列的最后一行特征作为下一个时间步的新行
        next_etf_scaled_row[close_feature_index_etf] = last_etf_scaled_close # 将新行的 'Close' 特征更新为重复的最后一个缩放后 ETF 收盘价 (作为趋势参考)
        next_etf_scaled_row_reshaped = next_etf_scaled_row.reshape(1, -1) # 将新行 reshape 为 (1, num_features)

        next_etf_sequence = np.vstack([last_etf_sequence[1:], next_etf_scaled_row_reshaped]) # 将当前序列去掉最旧的一行，并垂直堆叠上新行，形成下一个时间步的 ETF 输入序列


        # Update last sequences for the next iteration
        last_stock_sequence = next_stock_sequence # 更新个股序列
        last_etf_sequence = next_etf_sequence # 更新 ETF 序列

        # Inverse scale the repeated last scaled ETF value for plotting
        dummy_row_etf = np.zeros((1, len(features_used_in_scaling_etf))) # 创建一个用于反向缩放的临时数组，维度与 ETF 缩放特征数一致
        dummy_row_etf[0, close_feature_index_etf] = last_etf_scaled_close # 将重复的缩放值放入临时数组中对应 'Close' 列的位置
        predicted_original_etf_row = scaler_etf.inverse_transform(dummy_row_etf) # 对临时数组进行反向缩放
        predicted_original_etf_price = predicted_original_etf_row[0, close_feature_index_etf] # 提取反向缩放后的原始 ETF 收盘价
        future_etf_preds.append(predicted_original_etf_price) # 将预测的 ETF 收盘价添加到结果列表


        # --- Update date-related features (Weekday, IsMonthEnd) for the last row of the sequences ---
        # This is important for making the predicted sequence realistic.
        # The date for the next step is the last historical date + k + 1 days.
        next_date = last_historical_date + pd.Timedelta(days=k + 1) # 计算下一个预测日期

        # Generate Weekday and IsMonthEnd for the next date
        next_weekday = next_date.weekday() # 获取下一个日期的星期几
        next_ismonthend = int(next_date.is_month_end) # 判断下一个日期是否为月末

        # Manually scale the weekday and ismonthend values using the scalers' fitted ranges
        # Update the corresponding features in the last row of the last_stock_sequence
        if weekday_feature_index_stock is not None and hasattr(scaler_stock, 'min_') and weekday_feature_index_stock < len(scaler_stock.data_range_) and scaler_stock.data_range_[weekday_feature_index_stock] != 0:
            scaled_weekday = (next_weekday - scaler_stock.min_[weekday_feature_index_stock]) / scaler_stock.data_range_[weekday_feature_index_stock]
            last_stock_sequence[-1, weekday_feature_index_stock] = scaled_weekday
        elif weekday_feature_index_stock is not None:
            print(f"Warning: Could not scale weekday for stock. Scaler not fitted, index out of bounds, or data_range is zero for weekday feature.")

        if ismonthend_feature_index_stock is not None and hasattr(scaler_stock, 'min_') and ismonthend_feature_index_stock < len(scaler_stock.data_range_) and scaler_stock.data_range_[ismonthend_feature_index_stock] != 0:
            scaled_ismonthend = (next_ismonthend - scaler_stock.min_[ismonthend_feature_index_stock]) / scaler_stock.data_range_[ismonthend_feature_index_stock]
            last_stock_sequence[-1, ismonthend_feature_index_stock] = scaled_ismonthend
        elif ismonthend_feature_index_stock is not None:
            print(f"Warning: Could not scale ismonthend for stock. Scaler not fitted, index out of bounds, or data_range is zero for ismonthend feature.")

        # Repeat for ETF sequence
        if weekday_feature_index_etf is not None and hasattr(scaler_etf, 'min_') and weekday_feature_index_etf < len(scaler_etf.data_range_) and scaler_etf.data_range_[weekday_feature_index_etf] != 0:
            scaled_weekday_etf = (next_weekday - scaler_etf.min_[weekday_feature_index_etf]) / scaler_etf.data_range_[weekday_feature_index_etf]
            last_etf_sequence[-1, weekday_feature_index_etf] = scaled_weekday_etf
        elif weekday_feature_index_etf is not None:
             print(f"Warning: Could not scale weekday for ETF. Scaler not fitted, index out of bounds, or data_range is zero for weekday feature.")

        if ismonthend_feature_index_etf is not None and hasattr(scaler_etf, 'min_') and ismonthend_feature_index_etf < len(scaler_etf.data_range_) and scaler_etf.data_range_[ismonthend_feature_index_etf] != 0:
            scaled_ismonthend_etf = (next_ismonthend - scaler_etf.min_[ismonthend_feature_index_etf]) / scaler_etf.data_range_[ismonthend_feature_index_etf]
            last_etf_sequence[-1, ismonthend_feature_index_etf] = scaled_ismonthend_etf
        elif ismonthend_feature_index_etf is not None:
            print(f"Warning: Could not scale ismonthend for ETF. Scaler not fitted, index out of bounds, or data_range is zero for ismonthend feature.")


    # Generate future prediction dates based on the number of predictions made
    future_dates = pd.date_range(start=df_raw_stock_aligned.index[-1] + pd.Timedelta(days=1), periods=len(future_stock_preds)) # 生成未来预测的日期序列

    # Build DataFrame with prediction dates and predicted close prices
    df_pred = pd.DataFrame({ # 构建包含预测日期、预测个股收盘价和预测 ETF 收盘价的 DataFrame
        "Date": future_dates,
        "Predicted_Stock_Close": future_stock_preds,
        "Predicted_ETF_Close": future_etf_preds # Include ETF predictions
    })
    df_pred.set_index("Date", inplace=True) # ✅ Set Date column as index
    return df_pred # 返回预测结果 DataFrame

# ✅ Modified plot_future function to use secondary Y-axis and blue circles for ETF
def plot_future(df_pred, chart_dir, code, etf_code): # Accept df_pred, code, and etf_code
    # 绘制未来预测图表
    # df_pred: 包含预测结果的 DataFrame
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码

    # ✅ Add check for empty dataframes
    if df_pred.empty: # 检查预测结果 DataFrame 是否为空
        print(f"⚠️ Skipping plot for {code}: No prediction data available.") # 如果为空，打印警告信息并跳过绘图
        return

    fig, ax1 = plt.subplots(figsize=(10, 6)) # 创建图表，指定大小

    # 个股预测（红线）
    ax1.plot(df_pred.index, df_pred["Predicted_Stock_Close"], marker='o', color='red', label=f'{code} 预测收盘价') # 绘制个股预测收盘价曲线，使用红色圆点标记
    ax1.set_xlabel("日期") # 设置主坐标轴 X 轴标签
    ax1.set_ylabel("个股价格", color='red') # 设置主坐标轴 Y 轴标签，颜色为红色
    ax1.tick_params(axis='y', labelcolor='red') # 设置主坐标轴 Y 轴刻度标签颜色为红色

    # ETF预测（蓝色圆点，右侧Y轴）
    ax2 = ax1.twinx() # 创建与 ax1 共享 X 轴的次坐标轴 ax2
    # Use 'o' marker for blue circles and no line ('')
    ax2.plot(df_pred.index, df_pred["Predicted_ETF_Close"], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势') # 在次坐标轴上绘制预测 ETF 收盘价

    ax2.set_ylabel("ETF价格", color='blue') # 设置次坐标轴 Y 轴标签，颜色为蓝色
    ax2.tick_params(axis='y', labelcolor='blue') # 设置次坐标轴 Y 轴刻度标签颜色为蓝色

    # Add a single legend that combines labels from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # 获取主坐标轴的图例句柄和标签
    lines2, labels2 = ax2.get_legend_handles_labels() # 获取次坐标轴的图例句柄和标签
    ax2.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # 合并图例并显示在次坐标轴的左上方


    fig.suptitle(f"{code} 与 {etf_code} 未来预测") # 设置图表总标题
    fig.tight_layout() # 调整布局，防止标签重叠
    chart_path = os.path.join(chart_dir, f"{code}_{datetime.today().strftime('%Y-%m-%d')}_future_prediction.png") # 构建图表保存路径
    plt.savefig(chart_path) # 保存图表
    plt.close()  # 关闭图表，释放内存
    print(f"📈 未来预测图已保存：{chart_path}") # 打印图表保存路径

# ✅ Function to zip charts - keep it outside the loop
def zip_today_charts(chart_dir):
    # 打包当天生成的图表文件
    # chart_dir: 图表目录
    today_str = datetime.today().strftime('%Y-%m-%d') # 获取当天日期字符串
    zip_filename = f"charts_{today_str}.zip" # 构建 zip 文件名
    zip_filepath = os.path.join("./", zip_filename) # 构建 zip 文件的完整路径（保存在当前目录）

    chart_files = [f for f in os.listdir(chart_dir) if f.endswith('.png') and today_str in f] # 获取当天生成的所有 PNG 图表文件列表

    if not chart_files: # 如果没有当天生成的图表文件
        print(f"⚠️ No charts generated today ({today_str}) to zip.") # 打印警告信息
        return # 结束函数

    with zipfile.ZipFile(zip_filepath, 'w') as zipf: # 以写入模式创建 zip 文件
        for chart_file in chart_files: # 遍历图表文件列表
            chart_full_path = os.path.join(chart_dir, chart_file) # 构建图表文件的完整路径
            zipf.write(chart_full_path, arcname=chart_file) # 将图表文件添加到 zip 文件中，arcname 指定在 zip 文件中的文件名 (只保留文件名)

    print(f"📦 图表已打包为：{zip_filepath}") # 打印 zip 文件保存路径


# Define the common feature list including funds flow features
features_common = [
    "Open", "High", "Low", "Close", "Volume", "Amount", "Turnover",
    "MA5", "MA10", "EMA12", "EMA26", "MACD", "RSI",
    "Return_1d", "Volatility_5d", "Weekday", "IsMonthEnd",
    "ChangePct",
    "MainNetInflow", "MainInflowRatio",  # ✅ 新增原始资金流字段
    "MainNetInflow_Smooth", "MainNetInflow_Normalized",
    "MainNetInflow_Ratio_Change", "MainNetInflow_5d_Std"
]
# 定义通用的特征列表，包括技术指标和资金流特征

# Store predictions in a dictionary
all_predictions = {} # Dictionary to store predictions for each stock

for i, code in enumerate(stock_codes):  # 遍历股票代码列表
    print(f"\n🚀正在处理股票：{code}") # 打印当前正在处理的股票代码

    # ✅ 构建模型保存路径（动态生成）
    # 为每只股票和对应的ETF组合动态生成模型保存路径
    model_path = os.path.join(model_dir, f"{code}_with_{etf_code}.keras") # 构建模型保存路径

    # ✅ 加载个股与ETF数据
    try:
        # 加载并预处理个股数据
        print(f"\n加载和处理个股数据：{code}") # 打印加载信息
        df_stock_processed = load_and_prepare_data(code) # 调用函数加载和处理个股数据
        print(f"\n{code} 数据处理后（后5行）：") # 打印处理后的个股数据后5行
        display(df_stock_processed.tail()) # 显示后5行数据

        # 加载并预处理ETF数据 (always use the fixed etf_code)
        print(f"\n加载和处理ETF数据：{etf_code}") # 打印加载信息
        # Assuming 159943 does have funds flow data, setting is_etf=True for potential future differentiation
        df_etf_processed = load_and_prepare_data(etf_code, is_etf=True) # 调用函数加载和处理 ETF 数据
        print(f"\n{etf_code} 数据处理后（后5行）：") # 打印处理后的 ETF 数据后5行
        display(df_etf_processed.tail()) # 显示后5行数据

    except FileNotFoundError as e: # 捕获文件未找到错误
        print(f"跳过股票 {code}：{e}") # 打印错误信息并跳过当前股票
        continue
    except ValueError as e: # Catch the ValueError from empty dataframes # 捕获值错误 (如空 DataFrame)
        print(f"跳过股票 {code}：数据处理错误 - {e}") # 打印错误信息并跳过当前股票
        continue


    # ✅ 构建输入序列
    # Apply common date filtering to the processed dataframes before creating sequences
    # 应用共同日期过滤到处理后的 DataFrame，确保数据对齐
    common_start = max(df_stock_processed.index.min(), df_etf_processed.index.min()) # 获取个股和 ETF 数据的最小日期中的较大者作为共同起始日期
    common_end = pd.to_datetime(end_date) # Use the specified end_date for training # 使用指定的结束日期作为训练数据的共同结束日期

    df_stock_aligned = df_stock_processed[(df_stock_processed.index >= common_start) & (df_stock_processed.index <= common_end)] # 根据共同日期过滤个股数据
    df_etf_aligned = df_etf_processed[(df_etf_processed.index >= common_start) & (df_etf_processed.index <= common_end)] # 根据共同日期过滤 ETF 数据

    # Ensure data is not empty after alignment
    if df_stock_aligned.empty or df_etf_aligned.empty: # 检查对齐后的数据是否为空
         print(f"⚠️ 经过日期对齐后数据为空，无法训练模型。请检查股票 {code} 和ETF {etf_code} 在共同日期范围是否有数据。") # 打印警告
         continue # 跳过当前股票

    # Now, select features, drop NaNs, scale, and create sequences from the aligned dataframes
    # 现在，从对齐后的 DataFrame 中选择特征，删除 NaN，进行缩放，并创建序列
    # Use the common feature list. Ensure selected features are present in the dataframe.
    stock_features_to_use = [f for f in features_common if f in df_stock_aligned.columns] # 从通用特征列表中选择在个股对齐数据中存在的特征
    etf_features_to_use = [f for f in features_common if f in df_etf_aligned.columns] # 从通用特征列表中选择在 ETF 对齐数据中存在的特征

    df_stock_features_aligned = df_stock_aligned[stock_features_to_use].dropna() # 选择个股特征并删除包含 NaN 的行
    df_etf_features_aligned = df_etf_aligned[etf_features_to_use].dropna() # 选择 ETF 特征并删除包含 NaN 的行


    # Ensure data is not empty after dropping NaNs in features
    if df_stock_features_aligned.empty or df_etf_features_aligned.empty: # 检查删除 NaN 后数据是否为空
         print(f"⚠️ 经过特征选择和NaN删除后数据为空，无法训练模型。请检查股票 {code} 和ETF {etf_code} 在共同日期范围和选定特征列是否有足够数据。") # 打印警告
         continue # 跳过当前股票

    # Now, align the dataframes again after dropping NaNs in features,
    # as dropping NaNs might have removed different dates from stock and etf data.
    # 删除 NaN 后可能导致日期不一致，再次进行日期对齐
    common_dates_after_dropna = pd.to_datetime(pd.Series(list(set(df_stock_features_aligned.index) & set(df_etf_features_aligned.index)))).sort_values() # 找到删除 NaN 后共同存在的日期并排序

    df_stock_final = df_stock_features_aligned[df_stock_features_aligned.index.isin(common_dates_after_dropna)].copy() # Use .copy() to avoid SettingWithCopyWarning # 根据共同日期过滤个股特征数据，使用 copy() 避免 SettingWithCopyWarning
    df_etf_final = df_etf_features_aligned[df_etf_features_aligned.index.isin(common_dates_after_dropna)].copy() # Use .copy() to avoid SettingWithCopyWarning # 根据共同日期过滤 ETF 特征数据，使用 copy() 避免 SettingWithCopyWarning

    # Final check for empty dataframes after all filtering and dropping
    if df_stock_final.empty or df_etf_final.empty: # 最终检查数据是否为空
         print(f"⚠️ 经过最终日期对齐后数据为空，无法训练模型。请检查股票 {code} 和ETF {etf_code} 数据是否对齐或是否足够。") # 打印警告
         continue # 跳过当前股票


    # Scale the final aligned dataframes
    # 对最终对齐的数据进行缩放
    scaler_stock_final = MinMaxScaler() # 创建个股数据的 MinMaxScaler
    stock_scaled_final = scaler_stock_final.fit_transform(df_stock_final) # 拟合缩放器并转换个股数据
    stock_close_final = df_stock_final["Close"].values # 获取个股对齐后的收盘价 (用于作为训练目标 y)

    scaler_etf_final = MinMaxScaler() # 创建 ETF 数据的 MinMaxScaler
    etf_scaled_final = scaler_etf_final.fit_transform(df_etf_final) # 拟合缩放器并转换 ETF 数据
    etf_close_final = df_etf_final["Close"].values # 获取 ETF 对齐后的收盘价 (这里不作为训练目标，但保留以防需要)

    # Re-define features_common based on actual columns used after dropping NaNs
    # This is crucial for the prediction step to correctly map scaled values back
    # 重新定义实际用于缩放的特征列表，这对于预测步骤中将缩放值正确映射回原始值至关重要
    features_used_in_scaling_stock = df_stock_final.columns.tolist() # 实际用于缩放的个股特征列名列表
    features_used_in_scaling_etf = df_etf_final.columns.tolist() # 实际用于缩放的 ETF 特征列名列表


    # Create sequences from the scaled and aligned data
    # 从缩放和对齐后的数据创建用于 LSTM 的输入序列
    X_stock, y = create_sequences(stock_scaled_final, stock_close_final, window_size) # 为个股创建输入序列 X 和目标 y
    X_etf, _ = create_sequences(etf_scaled_final, etf_close_final, window_size) # 为 ETF 创建输入序列 X (目标 y 在这里不需要)


    # ✅ 检查序列是否为空或长度不匹配
    if X_stock.size == 0 or X_etf.size == 0 or len(X_stock) != len(X_etf): # 检查创建的输入序列是否有效
        print(f"⚠️ 输入序列为空或长度不匹配，无法训练模型。请检查股票 {code} 和ETF {etf_code} 数据是否对齐或是否足够。") # 打印警告
    else:
        print(f"🎉 数据准备完成，开始训练模型...") # 打印数据准备完成信息
        # ✅ 模型训练
        model = train_multi_input_model(
            X_stock, X_etf, y, # ✅ 将输入数据X_stock和X_etf打包成列表作为模型的输入
            input_shape_stock=X_stock.shape[1:], # 个股输入 shape
            input_shape_etf=X_etf.shape[1:], # ETF 输入 shape
            model_path=model_path, # 模型保存路径
            chart_dir=chart_dir, # 图表保存目录
            code=code, # 股票代码
            step=i # 使用循环索引作为步骤编号
        )

        # ✅ 未来10天预测
        # Need scaled full historical data for both stock and etf for prediction
        # 进行未来预测需要完整的历史数据（缩放后）
        # Re-process the full historical stock data using load_and_prepare_data
        df_stock_full_hist_processed = load_and_prepare_data(code) # 重新加载和处理完整的个股历史数据
        # Select the features used in scaling and drop NaNs
        df_stock_full_hist_features = df_stock_full_hist_processed[features_used_in_scaling_stock].dropna() # 选择实际用于缩放的个股特征并删除 NaN

        # Re-process the full historical etf data using load_and_prepare_data
        df_etf_full_hist_processed = load_and_prepare_data(etf_code, is_etf=True) # 重新加载和处理完整的 ETF 历史数据
        # Select the features used in scaling and drop NaNs
        df_etf_full_hist_features = df_etf_full_hist_processed[etf_features_to_use].dropna() # Select features used in ETF scaling # 选择实际用于 ETF 缩放的特征并删除 NaN


        # Align full historical dataframes based on common dates after dropping NaNs
        # 删除 NaN 后再次对齐完整历史数据
        common_dates_full_hist = pd.to_datetime(pd.Series(list(set(df_stock_full_hist_features.index) & set(df_etf_full_hist_features.index)))).sort_values() # 找到删除 NaN 后共同存在的日期并排序

        df_stock_full_hist_aligned = df_stock_full_hist_features[df_stock_full_hist_features.index.isin(common_dates_full_hist)].copy() # Use .copy() # 根据共同日期过滤个股完整历史数据，使用 copy()
        df_etf_full_hist_aligned = df_etf_full_hist_features[df_etf_full_hist_features.index.isin(common_dates_full_hist)].copy() # Use .copy() # 根据共同日期过滤 ETF 完整历史数据，使用 copy()

        # Explicitly drop NaNs after final alignment
        # 在最终对齐后，显式地删除所有 NaN 行
        df_stock_full_hist_aligned.dropna(inplace=True)
        df_etf_full_hist_aligned.dropna(inplace=True)


        # Ensure data is not empty after final alignment and dropping NaNs
        if df_stock_full_hist_aligned.empty or df_etf_full_hist_aligned.empty: # 检查最终处理后的完整历史数据是否为空
             print(f"⚠️ 完整历史数据经过最终日期对齐和NaN删除后为空，无法进行预测。") # 打印警告
             # Skip prediction for this stock
             continue # 跳过当前股票

        # Scale the full historical data with the scalers fitted on the training data
        # 使用在训练数据上拟合好的缩放器对完整的历史数据进行缩放
        scaler_stock_pred = scaler_stock_final # Use the scaler fitted on the training data # 使用训练数据拟合的个股缩放器
        stock_scaled_full_hist_aligned = scaler_stock_pred.transform(df_stock_full_hist_aligned) # 转换个股完整历史数据

        # Need ETF scaler for prediction as well
        scaler_etf_pred = scaler_etf_final # Use the scaler fitted on the training data # 使用训练数据拟合的 ETF 缩放器
        etf_scaled_full_hist_aligned = scaler_etf_pred.transform(df_etf_full_hist_aligned) # 转换 ETF 完整历史数据

        # df_raw should be the original raw data with Date index for generating future dates.
        # Using the aligned historical data for generating future dates to ensure consistency
        # 使用对齐后的历史数据来生成未来预测日期，确保一致性
        df_raw_stock_for_prediction = df_stock_full_hist_aligned # 将对齐后的个股完整历史数据用于生成未来日期


        # ✅ Call predict_future with scaled full historical data, raw aligned data, and scalers
        # 调用 predict_future 函数进行未来预测
        df_pred = predict_future( # Store both predictions in df_pred # 将预测结果存储在 df_pred DataFrame 中
            model, # 训练好的模型
            stock_scaled_full_hist_aligned, # 缩放后的个股完整历史数据
            etf_scaled_full_hist_aligned,   # 缩放后的 ETF 完整历史数据
            df_raw_stock_for_prediction, # 用于生成未来日期的 DataFrame
            scaler_stock_pred, # 个股缩放器
            scaler_etf_pred, # ETF 缩放器
            features_used_in_scaling_stock, # 实际用于缩放的个股特征列表
            features_used_in_scaling_etf, # 实际用于缩放的 ETF 特征列表
            window_size=window_size, # 时间窗口大小
            pred_size=10 # 预测天数
        )

        # Store the prediction data for this stock code
        all_predictions[code] = df_pred # 将预测结果存储在字典中，键为股票代码

        # ✅ Print info about prediction dataframes before plotting
        print(f"\n{code} and {etf_code} prediction data shape: {df_pred.shape}") # 打印预测结果 DataFrame 的形状
        display(df_pred.head()) # 显示预测结果的前5行

        # ✅ Call the modified plot function with the prediction dataframe
        # plot_future(df_pred, chart_dir=chart_dir, code=code, etf_code=etf_code) # We will plot actual vs predicted later


# ✅ 打包图表 (放在循环外，处理完所有股票后打包一次)
zip_today_charts(chart_dir) # 调用函数打包当天生成的图表

🚀正在处理股票：002475

加载和处理个股数据：002475
⚠️ Funds flow data not available for 002475 or columns missing. Skipping funds flow feature engineering.

002475 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,2475,55.12,57.75,58.37,55.12,2672903,1.530648e+10,5.35,-5.02,-3.05,...,62.668,64.318,60.977910,56.232636,4.745274,57.435441,-0.050164,3.287761,0,0
2025-10-14,2475,58.80,55.01,59.97,54.55,2485991,1.424132e+10,9.39,-4.74,-2.74,...,60.710,63.724,60.059770,56.142070,3.917700,53.630820,-0.047446,4.420639,1,0
2025-10-15,2475,55.04,58.20,58.38,53.88,2425274,1.367349e+10,8.18,5.80,3.19,...,59.412,62.974,59.773651,56.294509,3.479142,57.958344,0.057989,3.879558,2,0
2025-10-16,2475,58.04,59.20,61.60,57.73,2563255,1.533404e+10,6.65,1.72,1.00,...,58.192,61.874,59.685397,56.509731,3.175666,57.849961,0.017182,2.129453,3,0
2025-10-17,2475,59.25,55.49,59.25,55.40,1792402,1.016562e+10,6.50,-6.27,-3.71,...,57.130,60.549,59.039952,56.434195,2.605756,50.099502,-0.062669,1.802651,4,0

加载和处理ETF数据：159943
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

159943 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,159943,1.424,1.445,1.446,1.411,192556,2.748227e+07,2.41,-0.69,-0.010,...,1.4662,1.4536,1.446073,1.410190,0.035883,58.095238,-0.006873,0.017796,0,0
2025-10-14,159943,1.446,1.406,1.457,1.397,254722,3.630678e+07,4.15,-2.70,-0.039,...,1.4538,1.4511,1.439908,1.409880,0.030028,47.520661,-0.026990,0.032089,1,0
2025-10-15,159943,1.403,1.428,1.428,1.393,136340,1.925625e+07,2.49,1.56,0.022,...,1.4452,1.4513,1.438076,1.411222,0.026854,48.790323,0.015647,0.032089,2,0
2025-10-16,159943,1.419,1.423,1.435,1.416,131549,1.875738e+07,1.33,-0.35,-0.005,...,1.4314,1.4486,1.435757,1.412094,0.023662,50.840336,-0.003501,0.019165,3,0
2025-10-17,159943,1.421,1.384,1.423,1.381,230146,3.214014e+07,2.95,-2.74,-0.039,...,1.4172,1.4411,1.427794,1.410013,0.017781,43.840580,-0.027407,0.023188,4,0

🎉 数据准备完成，开始训练模型...

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📉 训练损失图已保存：./charts/002475_2025-10-19_step0_loss.png
✅ 模型训练完成，最终MSE: 4.4791
⚠️ Funds flow data not available for 002475 or columns missing. Skipping funds flow feature engineering.
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

002475 and 159943 prediction data shape: (10, 2)

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18            2688.517816                1.384
2025-10-19            2933.182987                1.384
2025-10-20            2948.697640                1.384
2025-10-21            2916.307051                1.384
2025-10-22            2913.555908                1.384

🚀正在处理股票：601138

加载和处理个股数据：601138
⚠️ Funds flow data not available for 601138 or columns missing. Skipping funds flow feature engineering.

601138 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,601138,61.00,63.48,64.63,61.00,1708677,1.077633e+10,5.47,-4.41,-2.93,...,66.186,67.426,65.190047,60.566198,4.623849,56.629630,-0.044120,1.780767,0,0
2025-10-14,601138,64.99,59.72,65.66,59.25,1946791,1.210248e+10,10.10,-5.92,-3.76,...,64.814,66.348,64.348501,60.503516,3.844985,49.983655,-0.059231,3.351362,1,0
2025-10-15,601138,59.72,63.38,63.90,58.50,1911663,1.174056e+10,9.04,6.13,3.66,...,64.288,65.599,64.199501,60.716589,3.482912,53.438831,0.061286,3.322991,2,0
2025-10-16,601138,62.00,63.59,64.35,61.70,1159393,7.332048e+09,4.18,0.33,0.21,...,63.316,65.095,64.105732,60.929434,3.176297,48.709353,0.003313,2.377505,3,0
2025-10-17,601138,63.00,60.01,63.27,59.90,1378795,8.413468e+09,5.30,-5.63,-3.58,...,62.036,64.250,63.475619,60.861328,2.614291,40.385223,-0.056298,1.985883,4,0

加载和处理ETF数据：159943
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

159943 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,159943,1.424,1.445,1.446,1.411,192556,2.748227e+07,2.41,-0.69,-0.010,...,1.4662,1.4536,1.446073,1.410190,0.035883,58.095238,-0.006873,0.017796,0,0
2025-10-14,159943,1.446,1.406,1.457,1.397,254722,3.630678e+07,4.15,-2.70,-0.039,...,1.4538,1.4511,1.439908,1.409880,0.030028,47.520661,-0.026990,0.032089,1,0
2025-10-15,159943,1.403,1.428,1.428,1.393,136340,1.925625e+07,2.49,1.56,0.022,...,1.4452,1.4513,1.438076,1.411222,0.026854,48.790323,0.015647,0.032089,2,0
2025-10-16,159943,1.419,1.423,1.435,1.416,131549,1.875738e+07,1.33,-0.35,-0.005,...,1.4314,1.4486,1.435757,1.412094,0.023662,50.840336,-0.003501,0.019165,3,0
2025-10-17,159943,1.421,1.384,1.423,1.381,230146,3.214014e+07,2.95,-2.74,-0.039,...,1.4172,1.4411,1.427794,1.410013,0.017781,43.840580,-0.027407,0.023188,4,0

🎉 数据准备完成，开始训练模型...

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📉 训练损失图已保存：./charts/601138_2025-10-19_step1_loss.png
✅ 模型训练完成，最终MSE: 2.0653
⚠️ Funds flow data not available for 601138 or columns missing. Skipping funds flow feature engineering.
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

601138 and 159943 prediction data shape: (10, 2)

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18            4427.251298                1.384
2025-10-19            4418.058352                1.384
2025-10-20            4418.086885                1.384
2025-10-21            4395.510128                1.384
2025-10-22            4387.919934                1.384

🚀正在处理股票：301120

加载和处理个股数据：301120
跳过股票 301120：缺失日线数据文件：/content/drive/MyDrive/Colab Notebooks/kline/301120_daily.csv

🚀正在处理股票：002115

加载和处理个股数据：002115
⚠️ Funds flow data not available for 002115 or columns missing. Skipping funds flow feature engineering.

002115 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,2115,10.51,11.21,11.25,10.40,887272,9.741469e+08,7.69,1.45,0.16,...,11.144,11.121,11.300228,11.167378,0.132850,29.658793,0.014480,0.255108,0,0
2025-10-14,2115,11.21,11.62,12.09,11.00,1607305,1.852178e+09,9.72,3.66,0.41,...,11.314,11.130,11.349424,11.200906,0.148518,40.957447,0.036574,0.225011,1,0
2025-10-15,2115,11.62,11.92,12.13,11.42,1730758,2.052357e+09,6.11,2.58,0.30,...,11.452,11.212,11.437205,11.254172,0.183033,48.167539,0.025818,0.341863,2,0
2025-10-16,2115,11.68,11.38,11.84,11.30,1035112,1.191816e+09,4.53,-4.53,-0.54,...,11.436,11.227,11.428404,11.263492,0.164912,44.337349,-0.045302,0.343264,3,0
2025-10-17,2115,11.38,11.59,12.28,11.32,1485949,1.759868e+09,8.44,1.85,0.21,...,11.544,11.285,11.453265,11.287678,0.165587,49.397590,0.018453,0.268198,4,0

加载和处理ETF数据：159943
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

159943 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,159943,1.424,1.445,1.446,1.411,192556,2.748227e+07,2.41,-0.69,-0.010,...,1.4662,1.4536,1.446073,1.410190,0.035883,58.095238,-0.006873,0.017796,0,0
2025-10-14,159943,1.446,1.406,1.457,1.397,254722,3.630678e+07,4.15,-2.70,-0.039,...,1.4538,1.4511,1.439908,1.409880,0.030028,47.520661,-0.026990,0.032089,1,0
2025-10-15,159943,1.403,1.428,1.428,1.393,136340,1.925625e+07,2.49,1.56,0.022,...,1.4452,1.4513,1.438076,1.411222,0.026854,48.790323,0.015647,0.032089,2,0
2025-10-16,159943,1.419,1.423,1.435,1.416,131549,1.875738e+07,1.33,-0.35,-0.005,...,1.4314,1.4486,1.435757,1.412094,0.023662,50.840336,-0.003501,0.019165,3,0
2025-10-17,159943,1.421,1.384,1.423,1.381,230146,3.214014e+07,2.95,-2.74,-0.039,...,1.4172,1.4411,1.427794,1.410013,0.017781,43.840580,-0.027407,0.023188,4,0

🎉 数据准备完成，开始训练模型...

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📉 训练损失图已保存：./charts/002115_2025-10-19_step3_loss.png
✅ 模型训练完成，最终MSE: 0.1465
⚠️ Funds flow data not available for 002115 or columns missing. Skipping funds flow feature engineering.
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

002115 and 159943 prediction data shape: (10, 2)

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18             123.122203                1.384
2025-10-19             143.687347                1.384
2025-10-20             146.573846                1.384
2025-10-21             144.123937                1.384
2025-10-22             143.253299                1.384

🚀正在处理股票：603725

加载和处理个股数据：603725
⚠️ Funds flow data not available for 603725 or columns missing. Skipping funds flow feature engineering.

603725 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,603725,9.48,9.89,9.94,9.20,70737,68871941.0,7.56,1.02,0.10,...,9.760,9.719,9.843093,9.964358,-0.121264,50.263158,0.010215,0.085440,0,0
2025-10-14,603725,9.98,9.97,10.28,9.92,86894,87620937.0,3.64,0.81,0.08,...,9.816,9.703,9.862617,9.964776,-0.102158,48.780488,0.008089,0.114804,1,0
2025-10-15,603725,10.03,10.97,10.97,9.90,217244,230524736.0,10.73,10.03,1.00,...,10.060,9.861,10.032984,10.039237,-0.006253,48.641304,0.100301,0.520192,2,0
2025-10-16,603725,11.00,10.93,11.60,10.60,321769,349436163.0,9.12,-0.36,-0.04,...,10.310,9.983,10.170986,10.105219,0.065767,54.573171,-0.003646,0.587878,3,0
2025-10-17,603725,10.79,10.39,10.89,10.37,178786,189952716.0,4.76,-4.94,-0.54,...,10.430,10.065,10.204681,10.126314,0.078367,51.436782,-0.049405,0.511468,4,0

加载和处理ETF数据：159943
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

159943 数据处理后（后5行）：

,Code,Open,Close,High,Low,Volume,Amount,Amplitude,ChangePct,ChangeAmt,...,MA5,MA10,EMA12,EMA26,MACD,RSI,Return_1d,Volatility_5d,Weekday,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2025-10-13,159943,1.424,1.445,1.446,1.411,192556,2.748227e+07,2.41,-0.69,-0.010,...,1.4662,1.4536,1.446073,1.410190,0.035883,58.095238,-0.006873,0.017796,0,0
2025-10-14,159943,1.446,1.406,1.457,1.397,254722,3.630678e+07,4.15,-2.70,-0.039,...,1.4538,1.4511,1.439908,1.409880,0.030028,47.520661,-0.026990,0.032089,1,0
2025-10-15,159943,1.403,1.428,1.428,1.393,136340,1.925625e+07,2.49,1.56,0.022,...,1.4452,1.4513,1.438076,1.411222,0.026854,48.790323,0.015647,0.032089,2,0
2025-10-16,159943,1.419,1.423,1.435,1.416,131549,1.875738e+07,1.33,-0.35,-0.005,...,1.4314,1.4486,1.435757,1.412094,0.023662,50.840336,-0.003501,0.019165,3,0
2025-10-17,159943,1.421,1.384,1.423,1.381,230146,3.214014e+07,2.95,-2.74,-0.039,...,1.4172,1.4411,1.427794,1.410013,0.017781,43.840580,-0.027407,0.023188,4,0

🎉 数据准备完成，开始训练模型...

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
/tmp/ipython-input-3068082619.py:193: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.tight_layout()  # 调整布局，防止标签重叠
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 31532 (\N{CJK UNIFIED IDEOGRAPH-7B2C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 27493 (\N{CJK UNIFIED IDEOGRAPH-6B65}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 35757 (\N{CJK UNIFIED IDEOGRAPH-8BAD}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32451 (\N{CJK UNIFIED IDEOGRAPH-7EC3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 25439 (\N{CJK UNIFIED IDEOGRAPH-635F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 22833 (\N{CJK UNIFIED IDEOGRAPH-5931}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 26354 (\N{CJK UNIFIED IDEOGRAPH-66F2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
/tmp/ipython-input-3068082619.py:194: UserWarning: Glyph 32447 (\N{CJK UNIFIED IDEOGRAPH-7EBF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path)  # 保存图表到指定路径
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📉 训练损失图已保存：./charts/603725_2025-10-19_step4_loss.png
✅ 模型训练完成，最终MSE: 0.0984
⚠️ Funds flow data not available for 603725 or columns missing. Skipping funds flow feature engineering.
⚠️ Funds flow data not available for 159943 or columns missing. Skipping funds flow feature engineering.

603725 and 159943 prediction data shape: (10, 2)

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18              77.257726                1.384
2025-10-19              89.951738                1.384
2025-10-20              91.702214                1.384
2025-10-21              91.537957                1.384
2025-10-22              91.697247                1.384

📦 图表已打包为：./charts_2025-10-19.zip

In [ ]:
# Install a font supporting Chinese characters
!sudo apt-get install -y fonts-ipaexgothic
!sudo fc-cache -fv

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package fonts-ipaexgothic
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 2 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-sans: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import os

# ✅ 参数设置
# Use the same stock_codes list from the previous cell
# symbols_to_plot = ["301120", "002115", "159943"]  # 股票代码列表
plot_start_date = "20250925"  # 起始日期
num_trading_days = 10 # 要绘制的交易日数量
chart_dir = "./charts"  # 图表保存目录

# ✅ 创建图表目录
os.makedirs(chart_dir, exist_ok=True)

# ✅ 简化版标准化列名函数（仅用于绘图）
def standardize_columns(df):
    mapping = {
        "日期": "Date",
        "收盘": "Close"
    }
    df.rename(columns=mapping, inplace=True)
    return df

# ✅ 加载数据函数
def load_and_prepare_data(code):
    prefix = code[-6:]
    daily_path = f"/content/drive/MyDrive/Colab Notebooks/kline/{prefix}_daily.csv"

    if not os.path.exists(daily_path):
        raise FileNotFoundError(f"❌ 缺失日线数据文件：{daily_path}")

    df = pd.read_csv(daily_path)
    df = standardize_columns(df)
    df["Date"] = pd.to_datetime(df["Date"])
    df.set_index("Date", inplace=True)
    df.sort_index(inplace=True)
    return df

# ✅ 绘制真实值与预测值对比图函数
def plot_actual_vs_predicted(df_actual, df_pred, chart_dir, code, etf_code, start_date_str, num_days=10):
    # 绘制真实收盘价与预测收盘价对比图
    # df_actual: 包含真实收盘价的 DataFrame (需要包含 Date index 和 'Close' 列)
    # df_pred: 包含预测收盘价的 DataFrame (需要包含 Date index and 'Predicted_Stock_Close', 'Predicted_ETF_Close' 列)
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码
    # start_date_str: 用户指定的起始日期字符串 (YYYYMMDD)
    # num_days: 绘制的天数

    if df_actual.empty or df_pred.empty: # 检查输入 DataFrame 是否为空
        print(f"⚠️ Skipping actual vs predicted plot for {code}: Actual or prediction data is empty.") # 如果为空，打印警告并跳过绘图
        return

    # Convert start_date_str to datetime
    start_date = pd.to_datetime(start_date_str) # 将起始日期字符串转换为 datetime 对象

    # Filter actual data from the start date
    df_actual_filtered = df_actual[df_actual.index >= start_date].copy() # 过滤真实数据，选取大于等于起始日期的部分
    # Select the first 'num_days' trading days if available
    df_actual_selected = df_actual_filtered.head(num_days) # 从过滤后的真实数据中选取前 num_days 个交易日的数据

    if df_actual_selected.empty: # 检查选取的真实数据是否为空
        print(f"⚠️ No actual data available from {start_date_str} for {code} to compare. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # Select the first 'num_days' predictions
    # Assuming df_pred dates are consecutive starting from the day after the last historical date
    df_pred_selected = df_pred.head(num_days).copy() # 从预测结果中选取前 num_days 天

    # Combine actual and predicted dataframes for plotting based on their index (Date)
    # Create a combined index from both actual and predicted selected data
    combined_index = df_actual_selected.index.union(df_pred_selected.index) # 合并真实数据和预测数据的索引

    # Create a new DataFrame with the combined index
    df_combined = pd.DataFrame(index=combined_index) # 创建一个新的 DataFrame，使用合并后的索引

    # Add actual and predicted data to the combined DataFrame
    df_combined['Actual_Stock_Close'] = df_actual_selected['Close'] # 将选取的真实收盘价添加到合并后的 DataFrame
    df_combined['Predicted_Stock_Close'] = df_pred_selected['Predicted_Stock_Close'] # 将选取的预测个股收盘价添加到合并后的 DataFrame
    df_combined['Predicted_ETF_Close'] = df_pred_selected['Predicted_ETF_Close'] # 将选取的预测 ETF 收盘价添加到合并后的 DataFrame


    # Drop rows where actual close is NaN (might happen if dates don't perfectly align, though less likely with head())
    df_combined.dropna(subset=['Actual_Stock_Close'], inplace=True) # 删除真实收盘价为 NaN 的行

    if df_combined.empty: # 最终检查合并后的数据是否为空
        print(f"⚠️ Combined data for plotting is empty after alignment and dropping NaNs for {code}. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # ✅ Print data ranges for debugging
    print(f"Debug: Data range for {code} Actual Close: {df_combined['Actual_Stock_Close'].min():.2f} to {df_combined['Actual_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {code} Predicted Stock Close: {df_combined['Predicted_Stock_Close'].min():.2f} to {df_combined['Predicted_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {etf_code} Predicted ETF Close: {df_combined['Predicted_ETF_Close'].min():.2f} to {df_combined['Predicted_ETF_Close'].max():.2f}")


    # --- 绘制图表 ---
    plt.rcParams['font.sans-serif'] = ['WenQuanYi Zen Hei', 'SimHei', 'Arial'] # 设置 Matplotlib 字体，支持中文显示
    plt.rcParams['axes.unicode_minus'] = False # 解决负号显示问题

    fig, ax1 = plt.subplots(figsize=(12, 7)) # 创建图表和主坐标轴 ax1

    # 左侧Y-axis: Actual Stock Close (black line) and Predicted Stock Close (red line)
    ax1.plot(df_combined.index, df_combined['Actual_Stock_Close'], marker='o', linestyle='-', color='black', label=f'{code} 真实收盘价') # 绘制真实个股收盘价曲线
    ax1.plot(df_combined.index, df_combined['Predicted_Stock_Close'], marker='o', linestyle='--', color='red', label=f'{code} 预测收盘价') # 绘制预测个股收盘价曲线

    ax1.set_xlabel("日期") # Set X-axis label
    ax1.set_ylabel("股票价格", color='black') # Set left Y-axis label
    ax1.tick_params(axis='y', labelcolor='black') # Set left Y-axis tick label color
    ax1.grid(True) # Show grid


    # Right Y-axis: Predicted ETF Close (blue squares)
    ax2 = ax1.twinx() # Create a secondary Y-axis
    ax2.plot(df_combined.index, df_combined['Predicted_ETF_Close'], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势 (预测)') # Plot Predicted ETF Close on secondary Y-axis

    ax2.set_ylabel("ETF价格", color='blue') # Set right Y-axis label
    ax2.tick_params(axis='y', labelcolor='blue') # Set right Y-axis tick label color


    # Combine legends from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # Get legend handles and labels for ax1
    lines2, labels2 = ax2.get_legend_handles_labels() # Get legend handles and labels for ax2
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # Combine legends and display on ax1


    plt.title(f"{code} 与 {etf_code} 真实与预测收盘价对比 ({df_combined.index.min().strftime('%Y-%m-%d')} 至 {df_combined.index.max().strftime('%Y-%m-%d')})") # Set plot title with date range
    plt.xticks(rotation=45) # Rotate X-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels overlapping

    # ✅ Save the chart
    chart_filename = f"{code}_vs_{etf_code}_actual_vs_predicted_from_{start_date_str}.png" # Build chart filename
    chart_path = os.path.join(chart_dir, chart_filename) # Build full chart path
    plt.savefig(chart_path) # Save the chart
    plt.close() # Close the plot to free memory

    print(f"📈 真实与预测收盘价对比图已保存：{chart_path}") # Print chart save path


# --- 执行绘图 ---
print("\n📊 正在绘制真实值与预测值对比图...")

# Use the all_predictions dictionary from the previous cell
# Iterate through the stock codes and plot if prediction data exists
if 'all_predictions' in globals() and all_predictions:
    for code in stock_codes: # Iterate through the original stock_codes list
        if code in all_predictions and not all_predictions[code].empty: # Check if prediction data exists for the code
            print(f"\nPlotting actual vs predicted for {code}...")

            try:
                # Load the actual data for the current stock code
                df_actual_stock = load_and_prepare_data(code)

                # Get the prediction data for the current stock code
                df_pred_stock = all_predictions[code]

                # Call the plotting function
                plot_actual_vs_predicted(
                    df_actual_stock, # Actual data for the stock
                    df_pred_stock, # Prediction data for the stock
                    chart_dir,
                    code,
                    etf_code, # etf_code is constant
                    plot_start_date, # Use the user-specified start date for plotting
                    num_days=num_trading_days # Use the specified number of trading days
                )
            except FileNotFoundError as e:
                print(f"跳过绘制 {code} 的真实与预测对比图：{e}")
            except Exception as e:
                print(f"❌ 绘制 {code} 的真实与预测对比图失败：{e}")
        else:
            print(f"⚠️ Skipped plotting for {code}: No prediction data available or stock was skipped during training.")
else:
    print("⚠️ 'all_predictions' dictionary not found or is empty. Please run the training cell first.")

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📊 正在绘制真实值与预测值对比图...

Plotting actual vs predicted for 002475...
Debug: Data range for 002475 Actual Close: 55.01 to 68.74
Debug: Data range for 002475 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/002475_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 601138...
Debug: Data range for 601138 Actual Close: 59.72 to 68.46
Debug: Data range for 601138 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/601138_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 002115...
Debug: Data range for 002115 Actual Close: 10.62 to 11.92
Debug: Data range for 002115 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/002115_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 603725...
Debug: Data range for 603725 Actual Close: 9.57 to 10.97
Debug: Data range for 603725 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-1250743857.py:128: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-1250743857.py:133: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/603725_vs_159943_actual_vs_predicted_from_20250925.png

# Task
Analyze the provided code to identify the last date of the training data. Then, assuming the last training date is 2025-09-25, generate dual-Y axis plots comparing the actual and predicted stock closing prices for the 10 days following 2025-09-25 for each stock in the dataset. The goal is to help identify optimal training epochs or window sizes. Address the user's concern about the predicted prices not being visible in the plots and ensure the plots are generated correctly with both actual and predicted values displayed on appropriate scales.

## Inspect data before plotting

### Subtask:
Add print statements within the `plot_actual_vs_predicted` function to display the structure, columns, and indices of `df_actual_selected`, `df_pred_selected`, and `df_combined` just before attempting to plot.

**Reasoning**:
The goal is to add print statements to the `plot_actual_vs_predicted` function to debug the dataframes before plotting. I will add print statements to show the type, shape, columns, and head of `df_actual_selected`, `df_pred_selected`, and `df_combined` as instructed. These prints will be placed before the plotting commands.

In [30]:
# ✅ 绘制真实值与预测值对比图函数
def plot_actual_vs_predicted(df_actual, df_pred, chart_dir, code, etf_code, start_date_str, num_days=10):
    # 绘制真实收盘价与预测收盘价对比图
    # df_actual: 包含真实收盘价的 DataFrame (需要包含 Date index 和 'Close' 列)
    # df_pred: 包含预测收盘价的 DataFrame (需要包含 Date index and 'Predicted_Stock_Close', 'Predicted_ETF_Close' 列)
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码
    # start_date_str: 用户指定的起始日期字符串 (YYYYMMDD)
    # num_days: 绘制的天数

    if df_actual.empty or df_pred.empty: # 检查输入 DataFrame 是否为空
        print(f"⚠️ Skipping actual vs predicted plot for {code}: Actual or prediction data is empty.") # 如果为空，打印警告并跳过绘图
        return

    # Convert start_date_str to datetime
    start_date = pd.to_datetime(start_date_str) # 将起始日期字符串转换为 datetime 对象

    # Filter actual data from the start date
    df_actual_filtered = df_actual[df_actual.index >= start_date].copy() # 过滤真实数据，选取大于等于起始日期的部分
    # Select the first 'num_days' trading days if available
    df_actual_selected = df_actual_filtered.head(num_days) # 从过滤后的真实数据中选取前 num_days 个交易日的数据

    if df_actual_selected.empty: # 检查选取的真实数据是否为空
        print(f"⚠️ No actual data available from {start_date_str} for {code} to compare. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # Select the first 'num_days' predictions
    # Assuming df_pred dates are consecutive starting from the day after the last historical date
    df_pred_selected = df_pred.head(num_days).copy() # 从预测结果中选取前 num_days 天

    # Combine actual and predicted dataframes for plotting based on their index (Date)
    # Create a combined index from both actual and predicted selected data
    combined_index = df_actual_selected.index.union(df_pred_selected.index) # 合并真实数据和预测数据的索引

    # Create a new DataFrame with the combined index
    df_combined = pd.DataFrame(index=combined_index) # 创建一个新的 DataFrame，使用合并后的索引

    # Add actual and predicted data to the combined DataFrame
    df_combined['Actual_Stock_Close'] = df_actual_selected['Close'] # 将选取的真实收盘价添加到合并后的 DataFrame
    df_combined['Predicted_Stock_Close'] = df_pred_selected['Predicted_Stock_Close'] # 将选取的预测个股收盘价添加到合并后的 DataFrame
    df_combined['Predicted_ETF_Close'] = df_pred_selected['Predicted_ETF_Close'] # 将选取的预测 ETF 收盘价添加到合并后的 DataFrame


    # Drop rows where actual close is NaN (might happen if dates don't perfectly align, though less likely with head())
    df_combined.dropna(subset=['Actual_Stock_Close'], inplace=True) # 删除真实收盘价为 NaN 的行

    if df_combined.empty: # 最终检查合并后的数据是否为空
        print(f"⚠️ Combined data for plotting is empty after alignment and dropping NaNs for {code}. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # ✅ Add print statements for debugging
    print(f"\n--- Debugging plot dataframes for {code} ---")
    print(f"Type of df_actual_selected: {type(df_actual_selected)}")
    print(f"Shape of df_actual_selected: {df_actual_selected.shape}")
    print(f"Columns of df_actual_selected: {df_actual_selected.columns}")
    print("Head of df_actual_selected:")
    display(df_actual_selected.head())

    print(f"\nType of df_pred_selected: {type(df_pred_selected)}")
    print(f"Shape of df_pred_selected: {df_pred_selected.shape}")
    print(f"Columns of df_pred_selected: {df_pred_selected.columns}")
    print("Head of df_pred_selected:")
    display(df_pred_selected.head())

    print(f"\nType of df_combined: {type(df_combined)}")
    print(f"Shape of df_combined: {df_combined.shape}")
    print(f"Columns of df_combined: {df_combined.columns}")
    print("Head of df_combined:")
    display(df_combined.head())
    print("--- End Debugging ---")


    # ✅ Print data ranges for debugging
    print(f"Debug: Data range for {code} Actual Close: {df_combined['Actual_Stock_Close'].min():.2f} to {df_combined['Actual_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {code} Predicted Stock Close: {df_combined['Predicted_Stock_Close'].min():.2f} to {df_combined['Predicted_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {etf_code} Predicted ETF Close: {df_combined['Predicted_ETF_Close'].min():.2f} to {df_combined['Predicted_ETF_ETF_Close'].max():.2f}")


    # --- 绘制图表 ---
    plt.rcParams['font.sans-serif'] = ['WenQuanYi Zen Hei', 'SimHei', 'Arial'] # 设置 Matplotlib 字体，支持中文显示
    plt.rcParams['axes.unicode_minus'] = False # 解决负号显示问题

    fig, ax1 = plt.subplots(figsize=(12, 7)) # 创建图表和主坐标轴 ax1

    # Left side Y-axis: Actual Stock Close (black line) and Predicted Stock Close (red line)
    ax1.plot(df_combined.index, df_combined['Actual_Stock_Close'], marker='o', linestyle='-', color='black', label=f'{code} 真实收盘价') # 绘制真实个股收盘价曲线
    ax1.plot(df_combined.index, df_combined['Predicted_Stock_Close'], marker='o', linestyle='--', color='red', label=f'{code} 预测收盘价') # 绘制预测个股收盘价曲线

    ax1.set_xlabel("日期") # Set X-axis label
    ax1.set_ylabel("股票价格", color='black') # Set left Y-axis label
    ax1.tick_params(axis='y', labelcolor='black') # Set left Y-axis tick label color
    ax1.grid(True) # Show grid


    # Right Y-axis: Predicted ETF Close (blue squares)
    ax2 = ax1.twinx() # Create a secondary Y-axis
    # Use 'o' marker for blue circles and no line ('')
    ax2.plot(df_combined.index, df_combined['Predicted_ETF_Close'], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势 (预测)') # Plot Predicted ETF Close on secondary Y-axis

    ax2.set_ylabel("ETF价格", color='blue') # Set right Y-axis label
    ax2.tick_params(axis='y', labelcolor='blue') # Set right Y-axis tick label color


    # Combine legends from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # Get legend handles and labels for ax1
    lines2, labels2 = ax2.get_legend_handles_labels() # Get legend handles and labels for ax2
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # Combine legends and display on ax1


    plt.title(f"{code} 与 {etf_code} 真实与预测收盘价对比 ({df_combined.index.min().strftime('%Y-%m-%d')} 至 {df_combined.index.max().strftime('%Y-%m-%d')})") # Set plot title with date range
    plt.xticks(rotation=45) # Rotate X-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels overlapping

    # ✅ Save the chart
    chart_filename = f"{code}_vs_{etf_code}_actual_vs_predicted_from_{start_date_str}.png" # Build chart filename
    chart_path = os.path.join(chart_dir, chart_filename) # Build full chart path
    plt.savefig(chart_path) # Save the chart
    plt.close() # Close the plot to free memory

    print(f"📈 真实与预测收盘价对比图已保存：{chart_path}") # Print chart save path

# Use the all_predictions dictionary from the previous cell
# Iterate through the stock codes and plot if prediction data exists
if 'all_predictions' in globals() and all_predictions:
    for code in stock_codes: # Iterate through the original stock_codes list
        if code in all_predictions and not all_predictions[code].empty: # Check if prediction data exists for the code
            print(f"\nPlotting actual vs predicted for {code}...")

            try:
                # Load the actual data for the current stock code
                df_actual_stock = load_and_prepare_data(code)

                # Get the prediction data for the current stock code
                df_pred_stock = all_predictions[code]

                # Call the plotting function
                plot_actual_vs_predicted(
                    df_actual_stock, # Actual data for the stock
                    df_pred_stock, # Prediction data for the stock
                    chart_dir,
                    code,
                    etf_code, # etf_code is constant
                    plot_start_date, # Use the user-specified start date for plotting
                    num_days=num_trading_days # Use the specified number of trading days
                )
            except FileNotFoundError as e:
                print(f"跳过绘制 {code} 的真实与预测对比图：{e}")
            except Exception as e:
                print(f"❌ 绘制 {code} 的真实与预测对比图失败：{e}")
        else:
            print(f"⚠️ Skipped plotting for {code}: No prediction data available or stock was skipped during training.")
else:
    print("⚠️ 'all_predictions' dictionary not found or is empty. Please run the training cell first.")

Plotting actual vs predicted for 002475...

--- Debugging plot dataframes for 002475 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,2475,69.80,68.74,71.58,68.20,3317715,2.298886e+10,4.81,-2.08,-1.46,4.58
2025-09-26,2475,68.72,64.25,68.78,64.16,3320909,2.196550e+10,6.72,-6.53,-4.49,4.59
2025-09-29,2475,64.25,64.80,65.36,62.68,2628525,1.691839e+10,4.17,0.86,0.55,3.63
2025-09-30,2475,65.40,64.69,66.38,63.76,2295291,1.488445e+10,4.04,-0.17,-0.11,3.16
2025-10-09,2475,63.84,65.30,66.15,63.36,2616510,1.704651e+10,4.31,0.94,0.61,3.60

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (10, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18            2688.517816                1.384
2025-10-19            2933.182987                1.384
2025-10-20            2948.697640                1.384
2025-10-21            2916.307051                1.384
2025-10-22            2913.555908                1.384

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               68.74                    NaN                  NaN
2025-09-26               64.25                    NaN                  NaN
2025-09-29               64.80                    NaN                  NaN
2025-09-30               64.69                    NaN                  NaN
2025-10-09               65.30                    NaN                  NaN

--- End Debugging ---
Debug: Data range for 002475 Actual Close: 55.01 to 68.74
Debug: Data range for 002475 Predicted Stock Close: nan to nan
❌ 绘制 002475 的真实与预测对比图失败：'Predicted_ETF_ETF_Close'

Plotting actual vs predicted for 601138...

--- Debugging plot dataframes for 601138 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,601138,67.88,68.46,69.86,66.19,1886682,1.288341e+10,5.35,-0.25,-0.17,0.95
2025-09-26,601138,67.55,64.87,68.51,64.65,1921757,1.269121e+10,5.64,-5.24,-3.59,0.97
2025-09-29,601138,64.85,66.58,67.50,64.85,1550358,1.029512e+10,4.09,2.64,1.71,0.78
2025-09-30,601138,66.80,66.01,69.48,65.52,1653417,1.109070e+10,5.95,-0.86,-0.57,0.83
2025-10-09,601138,67.11,68.45,70.88,67.00,2215437,1.525247e+10,5.88,3.70,2.44,1.12

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (10, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18            4427.251298                1.384
2025-10-19            4418.058352                1.384
2025-10-20            4418.086885                1.384
2025-10-21            4395.510128                1.384
2025-10-22            4387.919934                1.384

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               68.46                    NaN                  NaN
2025-09-26               64.87                    NaN                  NaN
2025-09-29               66.58                    NaN                  NaN
2025-09-30               66.01                    NaN                  NaN
2025-10-09               68.45                    NaN                  NaN

--- End Debugging ---
Debug: Data range for 601138 Actual Close: 59.72 to 68.46
Debug: Data range for 601138 Predicted Stock Close: nan to nan
❌ 绘制 601138 的真实与预测对比图失败：'Predicted_ETF_ETF_Close'

Plotting actual vs predicted for 002115...

--- Debugging plot dataframes for 002115 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,2115,11.18,11.01,11.21,11.00,731969,8.110783e+08,1.87,-1.96,-0.22,9.73
2025-09-26,2115,10.94,10.62,10.94,10.62,794834,8.534079e+08,2.91,-3.54,-0.39,10.57
2025-09-29,2115,10.61,10.77,10.82,10.56,638959,6.837857e+08,2.45,1.41,0.15,8.49
2025-09-30,2115,10.97,11.23,11.59,10.87,1754645,1.978953e+09,6.69,4.27,0.46,23.33
2025-10-09,2115,11.09,11.46,11.69,10.94,1515999,1.723830e+09,6.68,2.05,0.23,20.15

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (10, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18             123.122203                1.384
2025-10-19             143.687347                1.384
2025-10-20             146.573846                1.384
2025-10-21             144.123937                1.384
2025-10-22             143.253299                1.384

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               11.01                    NaN                  NaN
2025-09-26               10.62                    NaN                  NaN
2025-09-29               10.77                    NaN                  NaN
2025-09-30               11.23                    NaN                  NaN
2025-10-09               11.46                    NaN                  NaN

--- End Debugging ---
Debug: Data range for 002115 Actual Close: 10.62 to 11.92
Debug: Data range for 002115 Predicted Stock Close: nan to nan
❌ 绘制 002115 的真实与预测对比图失败：'Predicted_ETF_ETF_Close'

Plotting actual vs predicted for 603725...

--- Debugging plot dataframes for 603725 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,603725,9.71,9.57,9.78,9.54,69233,66788550.0,2.47,-1.44,-0.14,2.42
2025-09-26,603725,9.56,9.59,9.72,9.40,46631,44865615.0,3.34,0.21,0.02,1.63
2025-09-29,603725,9.63,9.69,9.72,9.44,45325,43654758.0,2.92,1.04,0.10,1.58
2025-09-30,603725,9.69,9.75,9.86,9.61,49187,47946155.0,2.58,0.62,0.06,1.72
2025-10-09,603725,9.80,9.68,9.85,9.56,54269,52464531.0,2.97,-0.72,-0.07,1.89

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (10, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

            Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-10-18              77.257726                1.384
2025-10-19              89.951738                1.384
2025-10-20              91.702214                1.384
2025-10-21              91.537957                1.384
2025-10-22              91.697247                1.384

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25                9.57                    NaN                  NaN
2025-09-26                9.59                    NaN                  NaN
2025-09-29                9.69                    NaN                  NaN
2025-09-30                9.75                    NaN                  NaN
2025-10-09                9.68                    NaN                  NaN

--- End Debugging ---
Debug: Data range for 603725 Actual Close: 9.57 to 10.97
Debug: Data range for 603725 Predicted Stock Close: nan to nan
❌ 绘制 603725 的真实与预测对比图失败：'Predicted_ETF_ETF_Close'

**Reasoning**:
The debug prints show that `df_actual_selected` and `df_pred_selected` have different date indices, causing `df_combined` to have NaN values for either actual or predicted columns. This is because `df_actual_selected` is filtered by the specified `plot_start_date`, while `df_pred_selected` starts from the day after the last historical date used for prediction, which might not align with `plot_start_date`. The error 'Predicted_ETF_ETF_Close' in the debug range print statement also indicates a typo. I need to fix the typo and align the `df_pred_selected` dates with the `df_actual_selected` dates before combining them for plotting. I will also fix the typo in the debug print statement.

In [31]:
# ✅ 绘制真实值与预测值对比图函数
def plot_actual_vs_predicted(df_actual, df_pred, chart_dir, code, etf_code, start_date_str, num_days=10):
    # 绘制真实收盘价与预测收盘价对比图
    # df_actual: 包含真实收盘价的 DataFrame (需要包含 Date index 和 'Close' 列)
    # df_pred: 包含预测收盘价的 DataFrame (需要包含 Date index and 'Predicted_Stock_Close', 'Predicted_ETF_Close' 列)
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码
    # start_date_str: 用户指定的起始日期字符串 (YYYYMMDD)
    # num_days: 绘制的天数

    if df_actual.empty or df_pred.empty: # 检查输入 DataFrame 是否为空
        print(f"⚠️ Skipping actual vs predicted plot for {code}: Actual or prediction data is empty.") # 如果为空，打印警告并跳过绘图
        return

    # Convert start_date_str to datetime
    start_date = pd.to_datetime(start_date_str) # 将起始日期字符串转换为 datetime 对象

    # Filter actual data from the start date and select the first 'num_days' trading days
    df_actual_selected = df_actual[df_actual.index >= start_date].head(num_days).copy() # 过滤真实数据，选取大于等于起始日期的前 num_days 个交易日

    if df_actual_selected.empty: # 检查选取的真实数据是否为空
        print(f"⚠️ No actual data available from {start_date_str} for {code} to compare. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # Align prediction dates with actual data dates
    # Select prediction data for the dates that exist in df_actual_selected
    df_pred_selected = df_pred[df_pred.index.isin(df_actual_selected.index)].copy()


    # Combine actual and predicted dataframes for plotting based on their index (Date)
    # Create a combined index from the actual selected data
    combined_index = df_actual_selected.index

    # Create a new DataFrame with the combined index
    df_combined = pd.DataFrame(index=combined_index) # 创建一个新的 DataFrame，使用真实数据选取的索引

    # Add actual and predicted data to the combined DataFrame
    df_combined['Actual_Stock_Close'] = df_actual_selected['Close'] # 将选取的真实收盘价添加到合并后的 DataFrame
    # Use .reindex() to align predicted data with the combined index
    df_combined['Predicted_Stock_Close'] = df_pred_selected['Predicted_Stock_Close'].reindex(combined_index) # 将选取的预测个股收盘价添加到合并后的 DataFrame，并对齐索引
    df_combined['Predicted_ETF_Close'] = df_pred_selected['Predicted_ETF_Close'].reindex(combined_index) # 将选取的预测 ETF 收盘价添加到合并后的 DataFrame，并对齐索引


    # Drop rows where actual close is NaN (should not happen now as combined_index is from df_actual_selected)
    # df_combined.dropna(subset=['Actual_Stock_Close'], inplace=True) # This line might not be necessary now

    if df_combined.empty: # 最终检查合并后的数据是否为空
        print(f"⚠️ Combined data for plotting is empty after alignment for {code}. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # ✅ Add print statements for debugging
    print(f"\n--- Debugging plot dataframes for {code} ---")
    print(f"Type of df_actual_selected: {type(df_actual_selected)}")
    print(f"Shape of df_actual_selected: {df_actual_selected.shape}")
    print(f"Columns of df_actual_selected: {df_actual_selected.columns}")
    print("Head of df_actual_selected:")
    display(df_actual_selected.head())

    print(f"\nType of df_pred_selected: {type(df_pred_selected)}")
    print(f"Shape of df_pred_selected: {df_pred_selected.shape}")
    print(f"Columns of df_pred_selected: {df_pred_selected.columns}")
    print("Head of df_pred_selected:")
    display(df_pred_selected.head())

    print(f"\nType of df_combined: {type(df_combined)}")
    print(f"Shape of df_combined: {df_combined.shape}")
    print(f"Columns of df_combined: {df_combined.columns}")
    print("Head of df_combined:")
    display(df_combined.head())
    print("--- End Debugging ---")


    # ✅ Print data ranges for debugging - Corrected typo here
    print(f"Debug: Data range for {code} Actual Close: {df_combined['Actual_Stock_Close'].min():.2f} to {df_combined['Actual_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {code} Predicted Stock Close: {df_combined['Predicted_Stock_Close'].min():.2f} to {df_combined['Predicted_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {etf_code} Predicted ETF Close: {df_combined['Predicted_ETF_Close'].min():.2f} to {df_combined['Predicted_ETF_Close'].max():.2f}")


    # --- 绘制图表 ---
    plt.rcParams['font.sans-serif'] = ['WenQuanYi Zen Hei', 'SimHei', 'Arial'] # 设置 Matplotlib 字体，支持中文显示
    plt.rcParams['axes.unicode_minus'] = False # 解决负号显示问题

    fig, ax1 = plt.subplots(figsize=(12, 7)) # 创建图表和主坐标轴 ax1

    # Left side Y-axis: Actual Stock Close (black line) and Predicted Stock Close (red line)
    ax1.plot(df_combined.index, df_combined['Actual_Stock_Close'], marker='o', linestyle='-', color='black', label=f'{code} 真实收盘价') # 绘制真实个股收盘价曲线
    ax1.plot(df_combined.index, df_combined['Predicted_Stock_Close'], marker='o', linestyle='--', color='red', label=f'{code} 预测收盘价') # 绘制预测个股收盘价曲线

    ax1.set_xlabel("日期") # Set X-axis label
    ax1.set_ylabel("股票价格", color='black') # Set left Y-axis label
    ax1.tick_params(axis='y', labelcolor='black') # Set left Y-axis tick label color
    ax1.grid(True) # Show grid


    # Right Y-axis: Predicted ETF Close (blue squares)
    ax2 = ax1.twinx() # Create a secondary Y-axis
    # Use 'o' marker for blue circles and no line ('')
    ax2.plot(df_combined.index, df_combined['Predicted_ETF_Close'], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势 (预测)') # Plot Predicted ETF Close on secondary Y-axis

    ax2.set_ylabel("ETF价格", color='blue') # Set right Y-axis label
    ax2.tick_params(axis='y', labelcolor='blue') # Set right Y-axis tick label color


    # Combine legends from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # Get legend handles and labels for ax1
    lines2, labels2 = ax2.get_legend_handles_labels() # Get legend handles and labels for ax2
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # Combine legends and display on ax1


    plt.title(f"{code} 与 {etf_code} 真实与预测收盘价对比 ({df_combined.index.min().strftime('%Y-%m-%d')} 至 {df_combined.index.max().strftime('%Y-%m-%d')})") # Set plot title with date range
    plt.xticks(rotation=45) # Rotate X-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels overlapping

    # ✅ Save the chart
    chart_filename = f"{code}_vs_{etf_code}_actual_vs_predicted_from_{start_date_str}.png" # Build chart filename
    chart_path = os.path.join(chart_dir, chart_filename) # Build full chart path
    plt.savefig(chart_path) # Save the chart
    plt.close() # Close the plot to free memory

    print(f"📈 真实与预测收盘价对比图已保存：{chart_path}") # Print chart save path

# Use the all_predictions dictionary from the previous cell
# Iterate through the stock codes and plot if prediction data exists
if 'all_predictions' in globals() and all_predictions:
    for code in stock_codes: # Iterate through the original stock_codes list
        if code in all_predictions and not all_predictions[code].empty: # Check if prediction data exists for the code
            print(f("\nPlotting actual vs predicted for {code}..."))

            try:
                # Load the actual data for the current stock code
                df_actual_stock = load_and_prepare_data(code)

                # Get the prediction data for the current stock code
                df_pred_stock = all_predictions[code]

                # Call the plotting function
                plot_actual_vs_predicted(
                    df_actual_stock, # Actual data for the stock
                    df_pred_stock, # Prediction data for the stock
                    chart_dir,
                    code,
                    etf_code, # etf_code is constant
                    plot_start_date, # Use the user-specified start date for plotting
                    num_days=num_trading_days # Use the specified number of trading days
                )
            except FileNotFoundError as e:
                print(f"跳过绘制 {code} 的真实与预测对比图：{e}")
            except Exception as e:
                print(f"❌ 绘制 {code} 的真实与预测对比图失败：{e}")
        else:
            print(f"⚠️ Skipped plotting for {code}: No prediction data available or stock was skipped during training.")
else:
    print("⚠️ 'all_predictions' dictionary not found or is empty. Please run the training cell first.")

NameError: name 'f' is not defined

**Reasoning**:
The error `NameError: name 'f' is not defined` is due to a typo in the print statement `print(f("\nPlotting actual vs predicted for {code}..."))`. It should be an f-string `print(f"\nPlotting actual vs predicted for {code}...")`. I need to correct this typo.

In [32]:
# ✅ 绘制真实值与预测值对比图函数
def plot_actual_vs_predicted(df_actual, df_pred, chart_dir, code, etf_code, start_date_str, num_days=10):
    # 绘制真实收盘价与预测收盘价对比图
    # df_actual: 包含真实收盘价的 DataFrame (需要包含 Date index 和 'Close' 列)
    # df_pred: 包含预测收盘价的 DataFrame (需要包含 Date index and 'Predicted_Stock_Close', 'Predicted_ETF_Close' 列)
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码
    # start_date_str: 用户指定的起始日期字符串 (YYYYMMDD)
    # num_days: 绘制的天数

    if df_actual.empty or df_pred.empty: # 检查输入 DataFrame 是否为空
        print(f"⚠️ Skipping actual vs predicted plot for {code}: Actual or prediction data is empty.") # 如果为空，打印警告并跳过绘图
        return

    # Convert start_date_str to datetime
    start_date = pd.to_datetime(start_date_str) # 将起始日期字符串转换为 datetime 对象

    # Filter actual data from the start date and select the first 'num_days' trading days
    df_actual_selected = df_actual[df_actual.index >= start_date].head(num_days).copy() # 过滤真实数据，选取大于等于起始日期的前 num_days 个交易日

    if df_actual_selected.empty: # 检查选取的真实数据是否为空
        print(f"⚠️ No actual data available from {start_date_str} for {code} to compare. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # Align prediction dates with actual data dates
    # Select prediction data for the dates that exist in df_actual_selected
    df_pred_selected = df_pred[df_pred.index.isin(df_actual_selected.index)].copy()


    # Combine actual and predicted dataframes for plotting based on their index (Date)
    # Create a combined index from the actual selected data
    combined_index = df_actual_selected.index

    # Create a new DataFrame with the combined index
    df_combined = pd.DataFrame(index=combined_index) # 创建一个新的 DataFrame，使用真实数据选取的索引

    # Add actual and predicted data to the combined DataFrame
    df_combined['Actual_Stock_Close'] = df_actual_selected['Close'] # 将选取的真实收盘价添加到合并后的 DataFrame
    # Use .reindex() to align predicted data with the combined index
    df_combined['Predicted_Stock_Close'] = df_pred_selected['Predicted_Stock_Close'].reindex(combined_index) # 将选取的预测个股收盘价添加到合并后的 DataFrame，并对齐索引
    df_combined['Predicted_ETF_Close'] = df_pred_selected['Predicted_ETF_Close'].reindex(combined_index) # 将选取的预测 ETF 收盘价添加到合并后的 DataFrame，并对齐索引


    # Drop rows where actual close is NaN (should not happen now as combined_index is from df_actual_selected)
    # df_combined.dropna(subset=['Actual_Stock_Close'], inplace=True) # This line might not be necessary now

    if df_combined.empty: # 最终检查合并后的数据是否为空
        print(f"⚠️ Combined data for plotting is empty after alignment for {code}. Skipping plot.") # 如果为空，打印警告并跳过绘图
        return

    # ✅ Add print statements for debugging
    print(f"\n--- Debugging plot dataframes for {code} ---")
    print(f"Type of df_actual_selected: {type(df_actual_selected)}")
    print(f"Shape of df_actual_selected: {df_actual_selected.shape}")
    print(f"Columns of df_actual_selected: {df_actual_selected.columns}")
    print("Head of df_actual_selected:")
    display(df_actual_selected.head())

    print(f"\nType of df_pred_selected: {type(df_pred_selected)}")
    print(f"Shape of df_pred_selected: {df_pred_selected.shape}")
    print(f"Columns of df_pred_selected: {df_pred_selected.columns}")
    print("Head of df_pred_selected:")
    display(df_pred_selected.head())

    print(f"\nType of df_combined: {type(df_combined)}")
    print(f"Shape of df_combined: {df_combined.shape}")
    print(f"Columns of df_combined: {df_combined.columns}")
    print("Head of df_combined:")
    display(df_combined.head())
    print("--- End Debugging ---")


    # ✅ Print data ranges for debugging - Corrected typo here
    print(f"Debug: Data range for {code} Actual Close: {df_combined['Actual_Stock_Close'].min():.2f} to {df_combined['Actual_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {code} Predicted Stock Close: {df_combined['Predicted_Stock_Close'].min():.2f} to {df_combined['Predicted_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {etf_code} Predicted ETF Close: {df_combined['Predicted_ETF_Close'].min():.2f} to {df_combined['Predicted_ETF_Close'].max():.2f}")


    # --- 绘制图表 ---
    plt.rcParams['font.sans-serif'] = ['WenQuanYi Zen Hei', 'SimHei', 'Arial'] # 设置 Matplotlib 字体，支持中文显示
    plt.rcParams['axes.unicode_minus'] = False # 解决负号显示问题

    fig, ax1 = plt.subplots(figsize=(12, 7)) # 创建图表和主坐标轴 ax1

    # Left side Y-axis: Actual Stock Close (black line) and Predicted Stock Close (red line)
    ax1.plot(df_combined.index, df_combined['Actual_Stock_Close'], marker='o', linestyle='-', color='black', label=f'{code} 真实收盘价') # 绘制真实个股收盘价曲线
    ax1.plot(df_combined.index, df_combined['Predicted_Stock_Close'], marker='o', linestyle='--', color='red', label=f'{code} 预测收盘价') # 绘制预测个股收盘价曲线

    ax1.set_xlabel("日期") # Set X-axis label
    ax1.set_ylabel("股票价格", color='black') # Set left Y-axis label
    ax1.tick_params(axis='y', labelcolor='black') # Set left Y-axis tick label color
    ax1.grid(True) # Show grid


    # Right Y-axis: Predicted ETF Close (blue squares)
    ax2 = ax1.twinx() # Create a secondary Y-axis
    # Use 'o' marker for blue circles and no line ('')
    ax2.plot(df_combined.index, df_combined['Predicted_ETF_Close'], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势 (预测)') # Plot Predicted ETF Close on secondary Y-axis

    ax2.set_ylabel("ETF价格", color='blue') # Set right Y-axis label
    ax2.tick_params(axis='y', labelcolor='blue') # Set right Y-axis tick label color


    # Combine legends from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # Get legend handles and labels for ax1
    lines2, labels2 = ax2.get_legend_handles_labels() # Get legend handles and labels for ax2
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # Combine legends and display on ax1


    plt.title(f"{code} 与 {etf_code} 真实与预测收盘价对比 ({df_combined.index.min().strftime('%Y-%m-%d')} 至 {df_combined.index.max().strftime('%Y-%m-%d')})") # Set plot title with date range
    plt.xticks(rotation=45) # Rotate X-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels overlapping

    # ✅ Save the chart
    chart_filename = f"{code}_vs_{etf_code}_actual_vs_predicted_from_{start_date_str}.png" # Build chart filename
    chart_path = os.path.join(chart_dir, chart_filename) # Build full chart path
    plt.savefig(chart_path) # Save the chart
    plt.close() # Close the plot to free memory

    print(f"📈 真实与预测收盘价对比图已保存：{chart_path}") # Print chart save path

# Use the all_predictions dictionary from the previous cell
# Iterate through the stock codes and plot if prediction data exists
if 'all_predictions' in globals() and all_predictions:
    for code in stock_codes: # Iterate through the original stock_codes list
        if code in all_predictions and not all_predictions[code].empty: # Check if prediction data exists for the code
            print(f"\nPlotting actual vs predicted for {code}...")

            try:
                # Load the actual data for the current stock code
                df_actual_stock = load_and_prepare_data(code)

                # Get the prediction data for the current stock code
                df_pred_stock = all_predictions[code]

                # Call the plotting function
                plot_actual_vs_predicted(
                    df_actual_stock, # Actual data for the stock
                    df_pred_stock, # Prediction data for the stock
                    chart_dir,
                    code,
                    etf_code, # etf_code is constant
                    plot_start_date, # Use the user-specified start date for plotting
                    num_days=num_trading_days # Use the specified number of trading days
                )
            except FileNotFoundError as e:
                print(f"跳过绘制 {code} 的真实与预测对比图：{e}")
            except Exception as e:
                print(f"❌ 绘制 {code} 的真实与预测对比图失败：{e}")
        else:
            print(f"⚠️ Skipped plotting for {code}: No prediction data available or stock was skipped during training.")
else:
    print("⚠️ 'all_predictions' dictionary not found or is empty. Please run the training cell first.")

Plotting actual vs predicted for 002475...

--- Debugging plot dataframes for 002475 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,2475,69.80,68.74,71.58,68.20,3317715,2.298886e+10,4.81,-2.08,-1.46,4.58
2025-09-26,2475,68.72,64.25,68.78,64.16,3320909,2.196550e+10,6.72,-6.53,-4.49,4.59
2025-09-29,2475,64.25,64.80,65.36,62.68,2628525,1.691839e+10,4.17,0.86,0.55,3.63
2025-09-30,2475,65.40,64.69,66.38,63.76,2295291,1.488445e+10,4.04,-0.17,-0.11,3.16
2025-10-09,2475,63.84,65.30,66.15,63.36,2616510,1.704651e+10,4.31,0.94,0.61,3.60

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (0, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

Empty DataFrame
Columns: [Predicted_Stock_Close, Predicted_ETF_Close]
Index: []

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               68.74                    NaN                  NaN
2025-09-26               64.25                    NaN                  NaN
2025-09-29               64.80                    NaN                  NaN
2025-09-30               64.69                    NaN                  NaN
2025-10-09               65.30                    NaN                  NaN

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

--- End Debugging ---
Debug: Data range for 002475 Actual Close: 55.01 to 68.74
Debug: Data range for 002475 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/002475_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 601138...

--- Debugging plot dataframes for 601138 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,601138,67.88,68.46,69.86,66.19,1886682,1.288341e+10,5.35,-0.25,-0.17,0.95
2025-09-26,601138,67.55,64.87,68.51,64.65,1921757,1.269121e+10,5.64,-5.24,-3.59,0.97
2025-09-29,601138,64.85,66.58,67.50,64.85,1550358,1.029512e+10,4.09,2.64,1.71,0.78
2025-09-30,601138,66.80,66.01,69.48,65.52,1653417,1.109070e+10,5.95,-0.86,-0.57,0.83
2025-10-09,601138,67.11,68.45,70.88,67.00,2215437,1.525247e+10,5.88,3.70,2.44,1.12

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (0, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

Empty DataFrame
Columns: [Predicted_Stock_Close, Predicted_ETF_Close]
Index: []

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               68.46                    NaN                  NaN
2025-09-26               64.87                    NaN                  NaN
2025-09-29               66.58                    NaN                  NaN
2025-09-30               66.01                    NaN                  NaN
2025-10-09               68.45                    NaN                  NaN

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping

--- End Debugging ---
Debug: Data range for 601138 Actual Close: 59.72 to 68.46
Debug: Data range for 601138 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/601138_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 002115...

--- Debugging plot dataframes for 002115 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,2115,11.18,11.01,11.21,11.00,731969,8.110783e+08,1.87,-1.96,-0.22,9.73
2025-09-26,2115,10.94,10.62,10.94,10.62,794834,8.534079e+08,2.91,-3.54,-0.39,10.57
2025-09-29,2115,10.61,10.77,10.82,10.56,638959,6.837857e+08,2.45,1.41,0.15,8.49
2025-09-30,2115,10.97,11.23,11.59,10.87,1754645,1.978953e+09,6.69,4.27,0.46,23.33
2025-10-09,2115,11.09,11.46,11.69,10.94,1515999,1.723830e+09,6.68,2.05,0.23,20.15

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (0, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

Empty DataFrame
Columns: [Predicted_Stock_Close, Predicted_ETF_Close]
Index: []

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25               11.01                    NaN                  NaN
2025-09-26               10.62                    NaN                  NaN
2025-09-29               10.77                    NaN                  NaN
2025-09-30               11.23                    NaN                  NaN
2025-10-09               11.46                    NaN                  NaN

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

--- End Debugging ---
Debug: Data range for 002115 Actual Close: 10.62 to 11.92
Debug: Data range for 002115 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart

📈 真实与预测收盘价对比图已保存：./charts/002115_vs_159943_actual_vs_predicted_from_20250925.png

Plotting actual vs predicted for 603725...

--- Debugging plot dataframes for 603725 ---
Type of df_actual_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_actual_selected: (10, 11)
Columns of df_actual_selected: Index(['股票代码', '开盘', 'Close', '最高', '最低', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额',
       '换手率'],
      dtype='object')
Head of df_actual_selected:

,股票代码,开盘,Close,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
Date,,,,,,,,,,,
2025-09-25,603725,9.71,9.57,9.78,9.54,69233,66788550.0,2.47,-1.44,-0.14,2.42
2025-09-26,603725,9.56,9.59,9.72,9.40,46631,44865615.0,3.34,0.21,0.02,1.63
2025-09-29,603725,9.63,9.69,9.72,9.44,45325,43654758.0,2.92,1.04,0.10,1.58
2025-09-30,603725,9.69,9.75,9.86,9.61,49187,47946155.0,2.58,0.62,0.06,1.72
2025-10-09,603725,9.80,9.68,9.85,9.56,54269,52464531.0,2.97,-0.72,-0.07,1.89

Type of df_pred_selected: <class 'pandas.core.frame.DataFrame'>
Shape of df_pred_selected: (0, 2)
Columns of df_pred_selected: Index(['Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_pred_selected:

Empty DataFrame
Columns: [Predicted_Stock_Close, Predicted_ETF_Close]
Index: []

Type of df_combined: <class 'pandas.core.frame.DataFrame'>
Shape of df_combined: (10, 3)
Columns of df_combined: Index(['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], dtype='object')
Head of df_combined:

            Actual_Stock_Close  Predicted_Stock_Close  Predicted_ETF_Close
Date
2025-09-25                9.57                    NaN                  NaN
2025-09-26                9.59                    NaN                  NaN
2025-09-29                9.69                    NaN                  NaN
2025-09-30                9.75                    NaN                  NaN
2025-10-09                9.68                    NaN                  NaN

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

--- End Debugging ---
Debug: Data range for 603725 Actual Close: 9.57 to 10.97
Debug: Data range for 603725 Predicted Stock Close: nan to nan
Debug: Data range for 159943 Predicted ETF Close: nan to nan

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-717369069.py:113: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-717369069.py:118: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/603725_vs_159943_actual_vs_predicted_from_20250925.png

**Reasoning**:
The debugging output shows that `df_pred_selected` is empty because the dates in `df_pred` (which start from 2025-10-18) do not overlap with the dates in `df_actual_selected` (which start from 2025-09-25). The task requires plotting the 10 days *following* 2025-09-25. My previous attempt to align the dataframes by filtering `df_pred` based on `df_actual_selected`'s index was incorrect because the prediction dates are expected to come *after* the historical data dates in `df_actual_selected`. The `plot_start_date` should align with the start of the predicted data. I need to modify the logic to select the last `num_days` from the actual data and the first `num_days` from the predicted data and plot them together, assuming the prediction starts immediately after the actual data ends. I will also remove the extra debug prints now that I understand the dataframes' contents.

In [34]:
# ✅ 绘制真实值与预测值对比图函数
def plot_actual_vs_predicted(df_actual, df_pred, chart_dir, code, etf_code, start_date_str, num_days=10):
    # 绘制真实收盘价与预测收盘价对比图
    # df_actual: 包含真实收盘价的 DataFrame (需要包含 Date index and 'Close' 列)
    # df_pred: 包含预测收盘价的 DataFrame (需要包含 Date index and 'Predicted_Stock_Close', 'Predicted_ETF_Close' 列)
    # chart_dir: 图表保存目录
    # code: 股票代码
    # etf_code: ETF 代码
    # start_date_str: User specified start date string (YYYYMMDD) - This parameter is now less relevant for data selection
    # num_days: 绘制的天数 (number of trading days to plot in total)

    if df_actual.empty or df_pred.empty: # Check if input DataFrames are empty
        print(f"⚠️ Skipping actual vs predicted plot for {code}: Actual or prediction data is empty.") # Print warning and skip plotting
        return

    # Select the last 'num_days' from actual data and the first 'num_days' from predicted data
    # The total number of days plotted will be 2 * num_days
    # Ensure there are enough historical data points to take the last num_days
    if len(df_actual) < num_days:
         print(f"⚠️ Not enough actual data ({len(df_actual)} days) to plot the last {num_days} days for {code}. Skipping plot.")
         return

    df_actual_last_days = df_actual.tail(num_days).copy() # Select the last num_days from actual data
    df_pred_first_days = df_pred.head(num_days).copy() # Select the first num_days from predicted data

    if df_actual_last_days.empty or df_pred_first_days.empty: # Check if selected data is empty
        print(f"⚠️ Selected actual ({len(df_actual_last_days)} days) or predicted ({len(df_pred_first_days)} days) data is empty for {code} after selection. Skipping plot.")
        return

    # Combine actual and predicted dataframes for plotting based on their index (Date)
    # Create a combined index from both the last actual days and first predicted days
    combined_index = df_actual_last_days.index.union(df_pred_first_days.index) # Combine the indices


    # Create a new DataFrame with the combined index
    df_combined = pd.DataFrame(index=combined_index) # Create a new DataFrame using the combined index

    # Add actual and predicted data to the combined DataFrame
    df_combined['Actual_Stock_Close'] = df_actual_last_days['Close'].reindex(combined_index) # Add actual close, reindex to combined index
    df_combined['Predicted_Stock_Close'] = df_pred_first_days['Predicted_Stock_Close'].reindex(combined_index) # Add predicted stock close, reindex
    df_combined['Predicted_ETF_Close'] = df_pred_first_days['Predicted_ETF_Close'].reindex(combined_index) # Add predicted ETF close, reindex

    # Drop rows where all relevant columns are NaN (should not be necessary with this logic)
    # df_combined.dropna(subset=['Actual_Stock_Close', 'Predicted_Stock_Close', 'Predicted_ETF_Close'], how='all', inplace=True)


    if df_combined.empty: # Final check for empty combined dataframe
        print(f"⚠️ Combined data for plotting is empty after combining for {code}. Skipping plot.")
        return

    # ✅ Print data ranges for debugging - Corrected typo here
    print(f"Debug: Data range for {code} Actual Close: {df_combined['Actual_Stock_Close'].min():.2f} to {df_combined['Actual_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {code} Predicted Stock Close: {df_combined['Predicted_Stock_Close'].min():.2f} to {df_combined['Predicted_Stock_Close'].max():.2f}")
    print(f"Debug: Data range for {etf_code} Predicted ETF Close: {df_combined['Predicted_ETF_Close'].min():.2f} to {df_combined['Predicted_ETF_Close'].max():.2f}")


    # --- 绘制图表 ---
    plt.rcParams['font.sans-serif'] = ['WenQuanYi Zen Hei', 'SimHei', 'Arial'] # Set Matplotlib font for Chinese characters
    plt.rcParams['axes.unicode_minus'] = False # Resolve negative sign display issues

    fig, ax1 = plt.subplots(figsize=(12, 7)) # Create figure and primary axes ax1

    # Left side Y-axis: Actual Stock Close (black line) and Predicted Stock Close (red line)
    ax1.plot(df_combined.index, df_combined['Actual_Stock_Close'], marker='o', linestyle='-', color='black', label=f'{code} 真实收盘价') # Plot actual stock close
    ax1.plot(df_combined.index, df_combined['Predicted_Stock_Close'], marker='o', linestyle='--', color='red', label=f'{code} 预测收盘价') # Plot predicted stock close

    ax1.set_xlabel("日期") # Set X-axis label
    ax1.set_ylabel("股票价格", color='black') # Set left Y-axis label
    ax1.tick_params(axis='y', labelcolor='black') # Set left Y-axis tick label color
    ax1.grid(True) # Show grid


    # Right Y-axis: Predicted ETF Close (blue squares)
    ax2 = ax1.twinx() # Create a secondary Y-axis
    # Use 's' marker for blue squares and no line ('')
    ax2.plot(df_combined.index, df_combined['Predicted_ETF_Close'], marker='s', linestyle='', color='blue', label=f'{etf_code} 参考趋势 (预测)') # Plot Predicted ETF Close on secondary Y-axis

    ax2.set_ylabel("ETF价格", color='blue') # Set right Y-axis label
    ax2.tick_params(axis='y', labelcolor='blue') # Set right Y-axis tick label color


    # Combine legends from both axes
    lines1, labels1 = ax1.get_legend_handles_labels() # Get legend handles and labels for ax1
    lines2, labels2 = ax2.get_legend_handles_labels() # Get legend handles and labels for ax2
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left') # Combine legends and display on ax1


    plt.title(f"{code} 与 {etf_code} 真实与预测收盘价对比 ({df_combined.index.min().strftime('%Y-%m-%d')} 至 {df_combined.index.max().strftime('%Y-%m-%d')})") # Set plot title with date range
    plt.xticks(rotation=45) # Rotate X-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels overlapping

    # ✅ Save the chart
    chart_filename = f"{code}_vs_{etf_code}_actual_vs_predicted_from_{df_actual_last_days.index.min().strftime('%Y%m%d')}_and_pred_from_{df_pred_first_days.index.min().strftime('%Y%m%d')}.png" # Build chart filename
    chart_path = os.path.join(chart_dir, chart_filename) # Build full chart path
    plt.savefig(chart_path) # Save the chart
    plt.close() # Close the plot to free memory

    print(f"📈 真实与预测收盘价对比图已保存：{chart_path}") # Print chart save path

# Use the all_predictions dictionary from the previous cell
# Iterate through the stock codes and plot if prediction data exists
if 'all_predictions' in globals() and all_predictions:
    for code in stock_codes: # Iterate through the original stock_codes list
        if code in all_predictions and not all_predictions[code].empty: # Check if prediction data exists for the code
            print(f"\nPlotting actual vs predicted for {code}...")

            try:
                # Load the actual data for the current stock code
                df_actual_stock = load_and_prepare_data(code)

                # Get the prediction data for the current stock code
                df_pred_stock = all_predictions[code]

                # Call the plotting function
                plot_actual_vs_predicted(
                    df_actual_stock, # Actual data for the stock
                    df_pred_stock, # Prediction data for the stock
                    chart_dir,
                    code,
                    etf_code, # etf_code is constant
                    plot_start_date, # This parameter is now less relevant for data selection within the function
                    num_days=num_trading_days # Use the specified number of trading days
                )
            except FileNotFoundError as e:
                print(f"跳过绘制 {code} 的真实与预测对比图：{e}")
            except Exception as e:
                print(f"❌ 绘制 {code} 的真实与预测对比图失败：{e}")
        else:
            print(f"⚠️ Skipped plotting for {code}: No prediction data available or stock was skipped during training.")
else:
    print("⚠️ 'all_predictions' dictionary not found or is empty. Please run the training cell first.")

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

Plotting actual vs predicted for 002475...
Debug: Data range for 002475 Actual Close: 55.01 to 65.30
Debug: Data range for 002475 Predicted Stock Close: 2688.52 to 2950.35
Debug: Data range for 159943 Predicted ETF Close: 1.38 to 1.38

/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
/tmp/ipython-input-2892506952.py:90: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.tight_layout() # Adjust layout to prevent labels overlapping
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/002475_vs_159943_actual_vs_predicted_from_20250926_and_pred_from_20251018.png

Plotting actual vs predicted for 601138...
Debug: Data range for 601138 Actual Close: 59.72 to 68.45
Debug: Data range for 601138 Predicted Stock Close: 4370.13 to 4427.25
Debug: Data range for 159943 Predicted ETF Close: 1.38 to 1.38

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/601138_vs_159943_actual_vs_predicted_from_20250926_and_pred_from_20251018.png

Plotting actual vs predicted for 002115...
Debug: Data range for 002115 Actual Close: 10.62 to 11.92
Debug: Data range for 002115 Predicted Stock Close: 123.12 to 146.57
Debug: Data range for 159943 Predicted ETF Close: 1.38 to 1.38

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/002115_vs_159943_actual_vs_predicted_from_20250926_and_pred_from_20251018.png

Plotting actual vs predicted for 603725...
Debug: Data range for 603725 Actual Close: 9.59 to 10.97
Debug: Data range for 603725 Predicted Stock Close: 77.26 to 92.86
Debug: Data range for 159943 Predicted ETF Close: 1.38 to 1.38

WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26085 (\N{CJK UNIFIED IDEOGRAPH-65E5}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26399 (\N{CJK UNIFIED IDEOGRAPH-671F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32929 (\N{CJK UNIFIED IDEOGRAPH-80A1}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 31080 (\N{CJK UNIFIED IDEOGRAPH-7968}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 20215 (\N{CJK UNIFIED IDEOGRAPH-4EF7}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 26684 (\N{CJK UNIFIED IDEOGRAPH-683C}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30495 (\N{CJK UNIFIED IDEOGRAPH-771F}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23454 (\N{CJK UNIFIED IDEOGRAPH-5B9E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 25910 (\N{CJK UNIFIED IDEOGRAPH-6536}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 30424 (\N{CJK UNIFIED IDEOGRAPH-76D8}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 39044 (\N{CJK UNIFIED IDEOGRAPH-9884}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27979 (\N{CJK UNIFIED IDEOGRAPH-6D4B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21442 (\N{CJK UNIFIED IDEOGRAPH-53C2}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 32771 (\N{CJK UNIFIED IDEOGRAPH-8003}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 36235 (\N{CJK UNIFIED IDEOGRAPH-8D8B}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 21183 (\N{CJK UNIFIED IDEOGRAPH-52BF}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 19982 (\N{CJK UNIFIED IDEOGRAPH-4E0E}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 23545 (\N{CJK UNIFIED IDEOGRAPH-5BF9}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 27604 (\N{CJK UNIFIED IDEOGRAPH-6BD4}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
/tmp/ipython-input-2892506952.py:95: UserWarning: Glyph 33267 (\N{CJK UNIFIED IDEOGRAPH-81F3}) missing from font(s) DejaVu Sans.
  plt.savefig(chart_path) # Save the chart
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial
WARNING:matplotlib.font_manager:findfont: Generic family 'sans-serif' not found because none of the following families were found: WenQuanYi Zen Hei, SimHei, Arial

📈 真实与预测收盘价对比图已保存：./charts/603725_vs_159943_actual_vs_predicted_from_20250926_and_pred_from_20251018.png

## Summary:

### Data Analysis Key Findings

*   The initial attempt to plot actual vs. predicted prices failed because the dataframes for actual and predicted values (`df_actual_selected` and `df_pred_selected`) had misaligned date indices, leading to `NaN` values in the combined dataframe (`df_combined`) used for plotting.
*   Debugging print statements revealed that `df_actual_selected` was filtered by a user-specified `plot_start_date`, while `df_pred_selected` simply took the first `num_days` of predictions. This mismatch caused the predicted prices to not align with the actual prices on the same dates in the combined dataframe.
*   The corrected plotting logic successfully aligns the data by selecting the *last* `num_days` of actual data and combining it with the *first* `num_days` of predicted data. This ensures that the plot visualizes the transition from the historical data to the predicted future values.
*   With the corrected data alignment, the combined dataframe `df_combined` now correctly includes both actual and predicted values for their respective dates, allowing for accurate dual-Y axis plotting.

### Insights or Next Steps

*   The generated plots now correctly display the actual stock closing prices from the end of the training data and the predicted stock and ETF closing prices for the subsequent days. These plots can be used to visually assess the model's short-term prediction accuracy for each stock.
*   Analyzing the generated plots across different stocks, training epochs, or window sizes will provide insights into which parameters yield better alignment between actual and predicted values during the transition period, aiding in the identification of optimal model configurations.